// Copyright (c) 2021 and onwards The vChewing Project (MIT-NTL License).
/*
Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

1. The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

2. No trademark license is granted to use the trade names, trademarks, service
marks, or product names of Contributor, except as required to fulfill notice
requirements above.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

import Foundation

extension String {
	mutating func regReplace(pattern: String, replaceWith: String = "") {
		// Ref: https://stackoverflow.com/a/40993403/4162914 && https://stackoverflow.com/a/71291137/4162914
		do {
			let regex = try NSRegularExpression(
				pattern: pattern, options: [.caseInsensitive, .anchorsMatchLines])
			let range = NSRange(self.startIndex..., in: self)
			self = regex.stringByReplacingMatches(
				in: self, options: [], range: range, withTemplate: replaceWith)
		} catch { return }
	}
	mutating func selfReplace(_ strOf: String, _ strWith: String = "") {
		self = self.replacingOccurrences(of: strOf, with: strWith)
	}
	mutating func formatConsolidate(cnvHYPYtoBPMF: Bool) {
		// Step 1: Consolidating formats per line.
		var strProcessed = self
		// 預處理格式
		strProcessed = strProcessed.replacingOccurrences(of: " #MACOS", with: "")  // 去掉 macOS 標記
		// CJKWhiteSpace (\x{3000}) to ASCII Space
		// NonBreakWhiteSpace (\x{A0}) to ASCII Space
		// Tab to ASCII Space
		// 統整連續空格為一個 ASCII 空格
		strProcessed.regReplace(pattern: #"( +|　+| +|\t+)+"#, replaceWith: " ")
		strProcessed.regReplace(pattern: #"(^ | $)"#, replaceWith: "")  // 去除行尾行首空格
		strProcessed.regReplace(pattern: #"(\f+|\r+|\n+)+"#, replaceWith: "\n")  // CR & FF to LF, 且去除重複行
		if strProcessed.prefix(1) == " " {  // 去除檔案開頭空格
			strProcessed.removeFirst()
		}
		if strProcessed.suffix(1) == " " {  // 去除檔案結尾空格
			strProcessed.removeLast()
		}
		var arrData = [""]
		if cnvHYPYtoBPMF {
			// Step 0: Convert HanyuPinyin to Bopomofo.
			arrData = strProcessed.components(separatedBy: "\n")
			strProcessed = ""  // Reset its value
			for lineData in arrData {
				var varLineData = lineData
				// 漢語拼音轉注音，得先從最長的可能的拼音組合開始轉起，
				// 這樣等轉換到更短的可能的漢語拼音組合時就不會出錯。
				// 依此類推，聲調放在最後來轉換。
				varLineData.selfReplace("chuang", "ㄔㄨㄤ")
				varLineData.selfReplace("shuang", "ㄕㄨㄤ")
				varLineData.selfReplace("zhuang", "ㄓㄨㄤ")
				varLineData.selfReplace("chang", "ㄔㄤ")
				varLineData.selfReplace("cheng", "ㄔㄥ")
				varLineData.selfReplace("chong", "ㄔㄨㄥ")
				varLineData.selfReplace("chuai", "ㄔㄨㄞ")
				varLineData.selfReplace("chuan", "ㄔㄨㄢ")
				varLineData.selfReplace("guang", "ㄍㄨㄤ")
				varLineData.selfReplace("huang", "ㄏㄨㄤ")
				varLineData.selfReplace("jiang", "ㄐㄧㄤ")
				varLineData.selfReplace("jiong", "ㄐㄩㄥ")
				varLineData.selfReplace("kuang", "ㄎㄨㄤ")
				varLineData.selfReplace("liang", "ㄌㄧㄤ")
				varLineData.selfReplace("niang", "ㄋㄧㄤ")
				varLineData.selfReplace("qiang", "ㄑㄧㄤ")
				varLineData.selfReplace("qiong", "ㄑㄩㄥ")
				varLineData.selfReplace("shang", "ㄕㄤ")
				varLineData.selfReplace("sheng", "ㄕㄥ")
				varLineData.selfReplace("shuai", "ㄕㄨㄞ")
				varLineData.selfReplace("shuan", "ㄕㄨㄢ")
				varLineData.selfReplace("xiang", "ㄒㄧㄤ")
				varLineData.selfReplace("xiong", "ㄒㄩㄥ")
				varLineData.selfReplace("zhang", "ㄓㄤ")
				varLineData.selfReplace("zheng", "ㄓㄥ")
				varLineData.selfReplace("zhong", "ㄓㄨㄥ")
				varLineData.selfReplace("zhuai", "ㄓㄨㄞ")
				varLineData.selfReplace("zhuan", "ㄓㄨㄢ")
				varLineData.selfReplace("bang", "ㄅㄤ")
				varLineData.selfReplace("beng", "ㄅㄥ")
				varLineData.selfReplace("bian", "ㄅㄧㄢ")
				varLineData.selfReplace("biao", "ㄅㄧㄠ")
				varLineData.selfReplace("bing", "ㄅㄧㄥ")
				varLineData.selfReplace("cang", "ㄘㄤ")
				varLineData.selfReplace("ceng", "ㄘㄥ")
				varLineData.selfReplace("chai", "ㄔㄞ")
				varLineData.selfReplace("chan", "ㄔㄢ")
				varLineData.selfReplace("chao", "ㄔㄠ")
				varLineData.selfReplace("chen", "ㄔㄣ")
				varLineData.selfReplace("chou", "ㄔㄡ")
				varLineData.selfReplace("chua", "ㄔㄨㄚ")
				varLineData.selfReplace("chui", "ㄔㄨㄟ")
				varLineData.selfReplace("chun", "ㄔㄨㄣ")
				varLineData.selfReplace("chuo", "ㄔㄨㄛ")
				varLineData.selfReplace("cong", "ㄘㄨㄥ")
				varLineData.selfReplace("cuan", "ㄘㄨㄢ")
				varLineData.selfReplace("dang", "ㄉㄤ")
				varLineData.selfReplace("deng", "ㄉㄥ")
				varLineData.selfReplace("dian", "ㄉㄧㄢ")
				varLineData.selfReplace("diao", "ㄉㄧㄠ")
				varLineData.selfReplace("ding", "ㄉㄧㄥ")
				varLineData.selfReplace("dong", "ㄉㄨㄥ")
				varLineData.selfReplace("duan", "ㄉㄨㄢ")
				varLineData.selfReplace("fang", "ㄈㄤ")
				varLineData.selfReplace("feng", "ㄈㄥ")
				varLineData.selfReplace("fiao", "ㄈㄧㄠ")
				varLineData.selfReplace("fong", "ㄈㄨㄥ")
				varLineData.selfReplace("gang", "ㄍㄤ")
				varLineData.selfReplace("geng", "ㄍㄥ")
				varLineData.selfReplace("giao", "ㄍㄧㄠ")
				varLineData.selfReplace("gong", "ㄍㄨㄥ")
				varLineData.selfReplace("guai", "ㄍㄨㄞ")
				varLineData.selfReplace("guan", "ㄍㄨㄢ")
				varLineData.selfReplace("hang", "ㄏㄤ")
				varLineData.selfReplace("heng", "ㄏㄥ")
				varLineData.selfReplace("hong", "ㄏㄨㄥ")
				varLineData.selfReplace("huai", "ㄏㄨㄞ")
				varLineData.selfReplace("huan", "ㄏㄨㄢ")
				varLineData.selfReplace("jian", "ㄐㄧㄢ")
				varLineData.selfReplace("jiao", "ㄐㄧㄠ")
				varLineData.selfReplace("jing", "ㄐㄧㄥ")
				varLineData.selfReplace("juan", "ㄐㄩㄢ")
				varLineData.selfReplace("kang", "ㄎㄤ")
				varLineData.selfReplace("keng", "ㄎㄥ")
				varLineData.selfReplace("kong", "ㄎㄨㄥ")
				varLineData.selfReplace("kuai", "ㄎㄨㄞ")
				varLineData.selfReplace("kuan", "ㄎㄨㄢ")
				varLineData.selfReplace("lang", "ㄌㄤ")
				varLineData.selfReplace("leng", "ㄌㄥ")
				varLineData.selfReplace("lian", "ㄌㄧㄢ")
				varLineData.selfReplace("liao", "ㄌㄧㄠ")
				varLineData.selfReplace("ling", "ㄌㄧㄥ")
				varLineData.selfReplace("long", "ㄌㄨㄥ")
				varLineData.selfReplace("luan", "ㄌㄨㄢ")
				varLineData.selfReplace("lvan", "ㄌㄩㄢ")
				varLineData.selfReplace("mang", "ㄇㄤ")
				varLineData.selfReplace("meng", "ㄇㄥ")
				varLineData.selfReplace("mian", "ㄇㄧㄢ")
				varLineData.selfReplace("miao", "ㄇㄧㄠ")
				varLineData.selfReplace("ming", "ㄇㄧㄥ")
				varLineData.selfReplace("nang", "ㄋㄤ")
				varLineData.selfReplace("neng", "ㄋㄥ")
				varLineData.selfReplace("nian", "ㄋㄧㄢ")
				varLineData.selfReplace("niao", "ㄋㄧㄠ")
				varLineData.selfReplace("ning", "ㄋㄧㄥ")
				varLineData.selfReplace("nong", "ㄋㄨㄥ")
				varLineData.selfReplace("nuan", "ㄋㄨㄢ")
				varLineData.selfReplace("pang", "ㄆㄤ")
				varLineData.selfReplace("peng", "ㄆㄥ")
				varLineData.selfReplace("pian", "ㄆㄧㄢ")
				varLineData.selfReplace("piao", "ㄆㄧㄠ")
				varLineData.selfReplace("ping", "ㄆㄧㄥ")
				varLineData.selfReplace("qian", "ㄑㄧㄢ")
				varLineData.selfReplace("qiao", "ㄑㄧㄠ")
				varLineData.selfReplace("qing", "ㄑㄧㄥ")
				varLineData.selfReplace("quan", "ㄑㄩㄢ")
				varLineData.selfReplace("rang", "ㄖㄤ")
				varLineData.selfReplace("reng", "ㄖㄥ")
				varLineData.selfReplace("rong", "ㄖㄨㄥ")
				varLineData.selfReplace("ruan", "ㄖㄨㄢ")
				varLineData.selfReplace("sang", "ㄙㄤ")
				varLineData.selfReplace("seng", "ㄙㄥ")
				varLineData.selfReplace("shai", "ㄕㄞ")
				varLineData.selfReplace("shan", "ㄕㄢ")
				varLineData.selfReplace("shao", "ㄕㄠ")
				varLineData.selfReplace("shei", "ㄕㄟ")
				varLineData.selfReplace("shen", "ㄕㄣ")
				varLineData.selfReplace("shou", "ㄕㄡ")
				varLineData.selfReplace("shua", "ㄕㄨㄚ")
				varLineData.selfReplace("shui", "ㄕㄨㄟ")
				varLineData.selfReplace("shun", "ㄕㄨㄣ")
				varLineData.selfReplace("shuo", "ㄕㄨㄛ")
				varLineData.selfReplace("song", "ㄙㄨㄥ")
				varLineData.selfReplace("suan", "ㄙㄨㄢ")
				varLineData.selfReplace("tang", "ㄊㄤ")
				varLineData.selfReplace("teng", "ㄊㄥ")
				varLineData.selfReplace("tian", "ㄊㄧㄢ")
				varLineData.selfReplace("tiao", "ㄊㄧㄠ")
				varLineData.selfReplace("ting", "ㄊㄧㄥ")
				varLineData.selfReplace("tong", "ㄊㄨㄥ")
				varLineData.selfReplace("tuan", "ㄊㄨㄢ")
				varLineData.selfReplace("wang", "ㄨㄤ")
				varLineData.selfReplace("weng", "ㄨㄥ")
				varLineData.selfReplace("xian", "ㄒㄧㄢ")
				varLineData.selfReplace("xiao", "ㄒㄧㄠ")
				varLineData.selfReplace("xing", "ㄒㄧㄥ")
				varLineData.selfReplace("xuan", "ㄒㄩㄢ")
				varLineData.selfReplace("yang", "ㄧㄤ")
				varLineData.selfReplace("ying", "ㄧㄥ")
				varLineData.selfReplace("yong", "ㄩㄥ")
				varLineData.selfReplace("yuan", "ㄩㄢ")
				varLineData.selfReplace("zang", "ㄗㄤ")
				varLineData.selfReplace("zeng", "ㄗㄥ")
				varLineData.selfReplace("zhai", "ㄓㄞ")
				varLineData.selfReplace("zhan", "ㄓㄢ")
				varLineData.selfReplace("zhao", "ㄓㄠ")
				varLineData.selfReplace("zhei", "ㄓㄟ")
				varLineData.selfReplace("zhen", "ㄓㄣ")
				varLineData.selfReplace("zhou", "ㄓㄡ")
				varLineData.selfReplace("zhua", "ㄓㄨㄚ")
				varLineData.selfReplace("zhui", "ㄓㄨㄟ")
				varLineData.selfReplace("zhun", "ㄓㄨㄣ")
				varLineData.selfReplace("zhuo", "ㄓㄨㄛ")
				varLineData.selfReplace("zong", "ㄗㄨㄥ")
				varLineData.selfReplace("zuan", "ㄗㄨㄢ")
				varLineData.selfReplace("jun", "ㄐㄩㄣ")
				varLineData.selfReplace("ang", "ㄤ")
				varLineData.selfReplace("bai", "ㄅㄞ")
				varLineData.selfReplace("ban", "ㄅㄢ")
				varLineData.selfReplace("bao", "ㄅㄠ")
				varLineData.selfReplace("bei", "ㄅㄟ")
				varLineData.selfReplace("ben", "ㄅㄣ")
				varLineData.selfReplace("bie", "ㄅㄧㄝ")
				varLineData.selfReplace("bin", "ㄅㄧㄣ")
				varLineData.selfReplace("cai", "ㄘㄞ")
				varLineData.selfReplace("can", "ㄘㄢ")
				varLineData.selfReplace("cao", "ㄘㄠ")
				varLineData.selfReplace("cei", "ㄘㄟ")
				varLineData.selfReplace("cen", "ㄘㄣ")
				varLineData.selfReplace("cha", "ㄔㄚ")
				varLineData.selfReplace("che", "ㄔㄜ")
				varLineData.selfReplace("chi", "ㄔ")
				varLineData.selfReplace("chu", "ㄔㄨ")
				varLineData.selfReplace("cou", "ㄘㄡ")
				varLineData.selfReplace("cui", "ㄘㄨㄟ")
				varLineData.selfReplace("cun", "ㄘㄨㄣ")
				varLineData.selfReplace("cuo", "ㄘㄨㄛ")
				varLineData.selfReplace("dai", "ㄉㄞ")
				varLineData.selfReplace("dan", "ㄉㄢ")
				varLineData.selfReplace("dao", "ㄉㄠ")
				varLineData.selfReplace("dei", "ㄉㄟ")
				varLineData.selfReplace("den", "ㄉㄣ")
				varLineData.selfReplace("dia", "ㄉㄧㄚ")
				varLineData.selfReplace("die", "ㄉㄧㄝ")
				varLineData.selfReplace("diu", "ㄉㄧㄡ")
				varLineData.selfReplace("dou", "ㄉㄡ")
				varLineData.selfReplace("dui", "ㄉㄨㄟ")
				varLineData.selfReplace("dun", "ㄉㄨㄣ")
				varLineData.selfReplace("duo", "ㄉㄨㄛ")
				varLineData.selfReplace("eng", "ㄥ")
				varLineData.selfReplace("fan", "ㄈㄢ")
				varLineData.selfReplace("fei", "ㄈㄟ")
				varLineData.selfReplace("fen", "ㄈㄣ")
				varLineData.selfReplace("fou", "ㄈㄡ")
				varLineData.selfReplace("gai", "ㄍㄞ")
				varLineData.selfReplace("gan", "ㄍㄢ")
				varLineData.selfReplace("gao", "ㄍㄠ")
				varLineData.selfReplace("gei", "ㄍㄟ")
				varLineData.selfReplace("gin", "ㄍㄧㄣ")
				varLineData.selfReplace("gen", "ㄍㄣ")
				varLineData.selfReplace("gou", "ㄍㄡ")
				varLineData.selfReplace("gua", "ㄍㄨㄚ")
				varLineData.selfReplace("gue", "ㄍㄨㄜ")
				varLineData.selfReplace("gui", "ㄍㄨㄟ")
				varLineData.selfReplace("gun", "ㄍㄨㄣ")
				varLineData.selfReplace("guo", "ㄍㄨㄛ")
				varLineData.selfReplace("hai", "ㄏㄞ")
				varLineData.selfReplace("han", "ㄏㄢ")
				varLineData.selfReplace("hao", "ㄏㄠ")
				varLineData.selfReplace("hei", "ㄏㄟ")
				varLineData.selfReplace("hen", "ㄏㄣ")
				varLineData.selfReplace("hou", "ㄏㄡ")
				varLineData.selfReplace("hua", "ㄏㄨㄚ")
				varLineData.selfReplace("hui", "ㄏㄨㄟ")
				varLineData.selfReplace("hun", "ㄏㄨㄣ")
				varLineData.selfReplace("huo", "ㄏㄨㄛ")
				varLineData.selfReplace("jia", "ㄐㄧㄚ")
				varLineData.selfReplace("jie", "ㄐㄧㄝ")
				varLineData.selfReplace("jin", "ㄐㄧㄣ")
				varLineData.selfReplace("jiu", "ㄐㄧㄡ")
				varLineData.selfReplace("jue", "ㄐㄩㄝ")
				varLineData.selfReplace("kai", "ㄎㄞ")
				varLineData.selfReplace("kan", "ㄎㄢ")
				varLineData.selfReplace("kao", "ㄎㄠ")
				varLineData.selfReplace("ken", "ㄎㄣ")
				varLineData.selfReplace("kiu", "ㄎㄧㄡ")
				varLineData.selfReplace("kou", "ㄎㄡ")
				varLineData.selfReplace("kua", "ㄎㄨㄚ")
				varLineData.selfReplace("kui", "ㄎㄨㄟ")
				varLineData.selfReplace("kun", "ㄎㄨㄣ")
				varLineData.selfReplace("kuo", "ㄎㄨㄛ")
				varLineData.selfReplace("lai", "ㄌㄞ")
				varLineData.selfReplace("lan", "ㄌㄢ")
				varLineData.selfReplace("lao", "ㄌㄠ")
				varLineData.selfReplace("lei", "ㄌㄟ")
				varLineData.selfReplace("lia", "ㄌㄧㄚ")
				varLineData.selfReplace("lie", "ㄌㄧㄝ")
				varLineData.selfReplace("lin", "ㄌㄧㄣ")
				varLineData.selfReplace("liu", "ㄌㄧㄡ")
				varLineData.selfReplace("lou", "ㄌㄡ")
				varLineData.selfReplace("lun", "ㄌㄨㄣ")
				varLineData.selfReplace("luo", "ㄌㄨㄛ")
				varLineData.selfReplace("lve", "ㄌㄩㄝ")
				varLineData.selfReplace("mai", "ㄇㄞ")
				varLineData.selfReplace("man", "ㄇㄢ")
				varLineData.selfReplace("mao", "ㄇㄠ")
				varLineData.selfReplace("mei", "ㄇㄟ")
				varLineData.selfReplace("men", "ㄇㄣ")
				varLineData.selfReplace("mie", "ㄇㄧㄝ")
				varLineData.selfReplace("min", "ㄇㄧㄣ")
				varLineData.selfReplace("miu", "ㄇㄧㄡ")
				varLineData.selfReplace("mou", "ㄇㄡ")
				varLineData.selfReplace("nai", "ㄋㄞ")
				varLineData.selfReplace("nan", "ㄋㄢ")
				varLineData.selfReplace("nao", "ㄋㄠ")
				varLineData.selfReplace("nei", "ㄋㄟ")
				varLineData.selfReplace("nen", "ㄋㄣ")
				varLineData.selfReplace("nie", "ㄋㄧㄝ")
				varLineData.selfReplace("nin", "ㄋㄧㄣ")
				varLineData.selfReplace("niu", "ㄋㄧㄡ")
				varLineData.selfReplace("nou", "ㄋㄡ")
				varLineData.selfReplace("nui", "ㄋㄨㄟ")
				varLineData.selfReplace("nun", "ㄋㄨㄣ")
				varLineData.selfReplace("nuo", "ㄋㄨㄛ")
				varLineData.selfReplace("nve", "ㄋㄩㄝ")
				varLineData.selfReplace("pai", "ㄆㄞ")
				varLineData.selfReplace("pan", "ㄆㄢ")
				varLineData.selfReplace("pao", "ㄆㄠ")
				varLineData.selfReplace("pei", "ㄆㄟ")
				varLineData.selfReplace("pen", "ㄆㄣ")
				varLineData.selfReplace("pia", "ㄆㄧㄚ")
				varLineData.selfReplace("pie", "ㄆㄧㄝ")
				varLineData.selfReplace("pin", "ㄆㄧㄣ")
				varLineData.selfReplace("pou", "ㄆㄡ")
				varLineData.selfReplace("qia", "ㄑㄧㄚ")
				varLineData.selfReplace("qie", "ㄑㄧㄝ")
				varLineData.selfReplace("qin", "ㄑㄧㄣ")
				varLineData.selfReplace("qiu", "ㄑㄧㄡ")
				varLineData.selfReplace("que", "ㄑㄩㄝ")
				varLineData.selfReplace("qun", "ㄑㄩㄣ")
				varLineData.selfReplace("ran", "ㄖㄢ")
				varLineData.selfReplace("rao", "ㄖㄠ")
				varLineData.selfReplace("ren", "ㄖㄣ")
				varLineData.selfReplace("rou", "ㄖㄡ")
				varLineData.selfReplace("rui", "ㄖㄨㄟ")
				varLineData.selfReplace("run", "ㄖㄨㄣ")
				varLineData.selfReplace("ruo", "ㄖㄨㄛ")
				varLineData.selfReplace("sai", "ㄙㄞ")
				varLineData.selfReplace("san", "ㄙㄢ")
				varLineData.selfReplace("sao", "ㄙㄠ")
				varLineData.selfReplace("sei", "ㄙㄟ")
				varLineData.selfReplace("sen", "ㄙㄣ")
				varLineData.selfReplace("sha", "ㄕㄚ")
				varLineData.selfReplace("she", "ㄕㄜ")
				varLineData.selfReplace("shi", "ㄕ")
				varLineData.selfReplace("shu", "ㄕㄨ")
				varLineData.selfReplace("sou", "ㄙㄡ")
				varLineData.selfReplace("sui", "ㄙㄨㄟ")
				varLineData.selfReplace("sun", "ㄙㄨㄣ")
				varLineData.selfReplace("suo", "ㄙㄨㄛ")
				varLineData.selfReplace("tai", "ㄊㄞ")
				varLineData.selfReplace("tan", "ㄊㄢ")
				varLineData.selfReplace("tao", "ㄊㄠ")
				varLineData.selfReplace("tie", "ㄊㄧㄝ")
				varLineData.selfReplace("tou", "ㄊㄡ")
				varLineData.selfReplace("tui", "ㄊㄨㄟ")
				varLineData.selfReplace("tun", "ㄊㄨㄣ")
				varLineData.selfReplace("tuo", "ㄊㄨㄛ")
				varLineData.selfReplace("wai", "ㄨㄞ")
				varLineData.selfReplace("wan", "ㄨㄢ")
				varLineData.selfReplace("wei", "ㄨㄟ")
				varLineData.selfReplace("wen", "ㄨㄣ")
				varLineData.selfReplace("xia", "ㄒㄧㄚ")
				varLineData.selfReplace("xie", "ㄒㄧㄝ")
				varLineData.selfReplace("xin", "ㄒㄧㄣ")
				varLineData.selfReplace("xiu", "ㄒㄧㄡ")
				varLineData.selfReplace("xue", "ㄒㄩㄝ")
				varLineData.selfReplace("xun", "ㄒㄩㄣ")
				varLineData.selfReplace("yai", "ㄧㄞ")
				varLineData.selfReplace("yan", "ㄧㄢ")
				varLineData.selfReplace("yao", "ㄧㄠ")
				varLineData.selfReplace("yin", "ㄧㄣ")
				varLineData.selfReplace("you", "ㄧㄡ")
				varLineData.selfReplace("yue", "ㄩㄝ")
				varLineData.selfReplace("yun", "ㄩㄣ")
				varLineData.selfReplace("zai", "ㄗㄞ")
				varLineData.selfReplace("zan", "ㄗㄢ")
				varLineData.selfReplace("zao", "ㄗㄠ")
				varLineData.selfReplace("zei", "ㄗㄟ")
				varLineData.selfReplace("zen", "ㄗㄣ")
				varLineData.selfReplace("zha", "ㄓㄚ")
				varLineData.selfReplace("zhe", "ㄓㄜ")
				varLineData.selfReplace("zhi", "ㄓ")
				varLineData.selfReplace("zhu", "ㄓㄨ")
				varLineData.selfReplace("zou", "ㄗㄡ")
				varLineData.selfReplace("zui", "ㄗㄨㄟ")
				varLineData.selfReplace("zun", "ㄗㄨㄣ")
				varLineData.selfReplace("zuo", "ㄗㄨㄛ")
				varLineData.selfReplace("ai", "ㄞ")
				varLineData.selfReplace("an", "ㄢ")
				varLineData.selfReplace("ao", "ㄠ")
				varLineData.selfReplace("ba", "ㄅㄚ")
				varLineData.selfReplace("bi", "ㄅㄧ")
				varLineData.selfReplace("bo", "ㄅㄛ")
				varLineData.selfReplace("bu", "ㄅㄨ")
				varLineData.selfReplace("ca", "ㄘㄚ")
				varLineData.selfReplace("ce", "ㄘㄜ")
				varLineData.selfReplace("ci", "ㄘ")
				varLineData.selfReplace("cu", "ㄘㄨ")
				varLineData.selfReplace("da", "ㄉㄚ")
				varLineData.selfReplace("de", "ㄉㄜ")
				varLineData.selfReplace("di", "ㄉㄧ")
				varLineData.selfReplace("du", "ㄉㄨ")
				varLineData.selfReplace("eh", "ㄝ")
				varLineData.selfReplace("ei", "ㄟ")
				varLineData.selfReplace("en", "ㄣ")
				varLineData.selfReplace("er", "ㄦ")
				varLineData.selfReplace("fa", "ㄈㄚ")
				varLineData.selfReplace("fo", "ㄈㄛ")
				varLineData.selfReplace("fu", "ㄈㄨ")
				varLineData.selfReplace("ga", "ㄍㄚ")
				varLineData.selfReplace("ge", "ㄍㄜ")
				varLineData.selfReplace("gi", "ㄍㄧ")
				varLineData.selfReplace("gu", "ㄍㄨ")
				varLineData.selfReplace("ha", "ㄏㄚ")
				varLineData.selfReplace("he", "ㄏㄜ")
				varLineData.selfReplace("hu", "ㄏㄨ")
				varLineData.selfReplace("ji", "ㄐㄧ")
				varLineData.selfReplace("ju", "ㄐㄩ")
				varLineData.selfReplace("ka", "ㄎㄚ")
				varLineData.selfReplace("ke", "ㄎㄜ")
				varLineData.selfReplace("ku", "ㄎㄨ")
				varLineData.selfReplace("la", "ㄌㄚ")
				varLineData.selfReplace("le", "ㄌㄜ")
				varLineData.selfReplace("li", "ㄌㄧ")
				varLineData.selfReplace("lo", "ㄌㄛ")
				varLineData.selfReplace("lu", "ㄌㄨ")
				varLineData.selfReplace("lv", "ㄌㄩ")
				varLineData.selfReplace("ma", "ㄇㄚ")
				varLineData.selfReplace("me", "ㄇㄜ")
				varLineData.selfReplace("mi", "ㄇㄧ")
				varLineData.selfReplace("mo", "ㄇㄛ")
				varLineData.selfReplace("mu", "ㄇㄨ")
				varLineData.selfReplace("na", "ㄋㄚ")
				varLineData.selfReplace("ne", "ㄋㄜ")
				varLineData.selfReplace("ni", "ㄋㄧ")
				varLineData.selfReplace("nu", "ㄋㄨ")
				varLineData.selfReplace("nv", "ㄋㄩ")
				varLineData.selfReplace("ou", "ㄡ")
				varLineData.selfReplace("pa", "ㄆㄚ")
				varLineData.selfReplace("pi", "ㄆㄧ")
				varLineData.selfReplace("po", "ㄆㄛ")
				varLineData.selfReplace("pu", "ㄆㄨ")
				varLineData.selfReplace("qi", "ㄑㄧ")
				varLineData.selfReplace("qu", "ㄑㄩ")
				varLineData.selfReplace("re", "ㄖㄜ")
				varLineData.selfReplace("ri", "ㄖ")
				varLineData.selfReplace("ru", "ㄖㄨ")
				varLineData.selfReplace("sa", "ㄙㄚ")
				varLineData.selfReplace("se", "ㄙㄜ")
				varLineData.selfReplace("si", "ㄙ")
				varLineData.selfReplace("su", "ㄙㄨ")
				varLineData.selfReplace("ta", "ㄊㄚ")
				varLineData.selfReplace("te", "ㄊㄜ")
				varLineData.selfReplace("ti", "ㄊㄧ")
				varLineData.selfReplace("tu", "ㄊㄨ")
				varLineData.selfReplace("wa", "ㄨㄚ")
				varLineData.selfReplace("wo", "ㄨㄛ")
				varLineData.selfReplace("wu", "ㄨ")
				varLineData.selfReplace("xi", "ㄒㄧ")
				varLineData.selfReplace("xu", "ㄒㄩ")
				varLineData.selfReplace("ya", "ㄧㄚ")
				varLineData.selfReplace("ye", "ㄧㄝ")
				varLineData.selfReplace("yi", "ㄧ")
				varLineData.selfReplace("yo", "ㄧㄛ")
				varLineData.selfReplace("yu", "ㄩ")
				varLineData.selfReplace("za", "ㄗㄚ")
				varLineData.selfReplace("ze", "ㄗㄜ")
				varLineData.selfReplace("zi", "ㄗ")
				varLineData.selfReplace("zu", "ㄗㄨ")
				varLineData.selfReplace("a", "ㄚ")
				varLineData.selfReplace("e", "ㄜ")
				varLineData.selfReplace("o", "ㄛ")
				varLineData.selfReplace("q", "ㄑ")
				varLineData.selfReplace("2", "ˊ")
				varLineData.selfReplace("3", "ˇ")
				varLineData.selfReplace("4", "ˋ")
				varLineData.selfReplace("5", "˙")
				varLineData.selfReplace("1", "")
				strProcessed += varLineData
				strProcessed += "\n"
			}
		}

		// Step 3: Add Formatted Pragma, the Sorted Header:
		let hdrFormatted = "# 𝙵𝙾𝚁𝙼𝙰𝚃 𝚘𝚛𝚐.𝚊𝚝𝚎𝚕𝚒𝚎𝚛𝙸𝚗𝚖𝚞.𝚟𝚌𝚑𝚎𝚠𝚒𝚗𝚐.𝚞𝚜𝚎𝚛𝙻𝚊𝚗𝚐𝚞𝚊𝚐𝚎𝙼𝚘𝚍𝚎𝚕𝙳𝚊𝚝𝚊.𝚏𝚘𝚛𝚖𝚊𝚝𝚝𝚎𝚍\n"
		strProcessed = hdrFormatted + strProcessed  // Add Sorted Header

		// Step 4: Deduplication.
		arrData = strProcessed.components(separatedBy: "\n")
		strProcessed = ""  // Reset its value
		// 下面兩行的 reversed 是首尾顛倒，免得破壞最新的 override 資訊。
		let arrDataDeduplicated = Array(NSOrderedSet(array: arrData.reversed()).array as! [String])
		for lineData in arrDataDeduplicated.reversed() {
			strProcessed += lineData
			strProcessed += "\n"
		}

		// Step 5: Remove duplicated newlines at the end of the file.
		strProcessed.regReplace(pattern: "\\n+", replaceWith: "\n")

		// Step 6: Commit Formatted Contents.
		self = strProcessed
	}
}
