// (c) 2022 and onwards The vChewing Project (LGPL v3.0 License or later).
// ====================
// This code is released under the SPDX-License-Identifier: `LGPL-3.0-or-later`.

let testTable4DynamicLayouts = """
$READING Dachen26 ETen26 Hsu Starlight AlvinLiu
ㄅㄚ qquu ba by ba ba
ㄅㄚˇ qquur baj byf ba8 baj
ㄅㄚˊ qquue baf byd ba7 baf
ㄅㄚˋ qquud bak byj ba9 bal
ㄅㄚ˙ qquuy bad bys ba0 bad
ㄅㄛ qqi bo bh bo bo
ㄅㄛˇ qqir boj bhf bo8 boj
ㄅㄛˊ qqie bof bhd bo7 bof
ㄅㄛˋ qqid bok bhj bo9 bol
ㄅㄛ˙ qqiy bod bhs bo0 bod
ㄅㄞ qqii bi bi by bh
ㄅㄞˇ qqiir bij bif by8 bhj
ㄅㄞˊ qqiie bif bid by7 bhf
ㄅㄞˋ qqiid bik bij by9 bhl
ㄅㄞ˙ qqiiy bid bis by0 bhd
ㄅㄟ qqo bq ba bt bk
ㄅㄟˇ qqor bqj baf bt8 bkj
ㄅㄟˋ qqod bqk baj bt9 bkl
ㄅㄟ˙ qqoy bqd bas bt0 bkd
ㄅㄠ qql bz bw bf bw
ㄅㄠˇ qqlr bzj bwf bf8 bwj
ㄅㄠˊ qqle bzf bwd bf7 bwf
ㄅㄠˋ qqld bzk bwj bf9 bwl
ㄅㄢ qqoo bm bm bm bb
ㄅㄢˇ qqoor bmj bmf bm8 bbj
ㄅㄢˋ qqood bmk bmj bm9 bbl
ㄅㄣ qqp bn bn bn bn
ㄅㄣˇ qqpr bnj bnf bn8 bnj
ㄅㄣˋ qqpd bnk bnj bn9 bnl
ㄅㄤ qqll bt bk bk bg
ㄅㄤˇ qqllr btj bkf bk8 bgj
ㄅㄤˋ qqlld btk bkj bk9 bgl
ㄅㄥ qqn bl bl bg bm
ㄅㄥˇ qqnr blj blf bg8 bmj
ㄅㄥˊ qqne blf bld bg7 bmf
ㄅㄥˋ qqnd blk blj bg9 bml
ㄅㄧ qqu be be bi bi
ㄅㄧㄝ qqub bew bee bie bic
ㄅㄧㄝˇ qqubr bewj beef bie8 bicj
ㄅㄧㄝˊ qqube bewf beed bie7 bicf
ㄅㄧㄝˋ qqubd bewk beej bie9 bicl
ㄅㄧㄠ qqul bez bew bif biw
ㄅㄧㄠˇ qqulr bezj bewf bif8 biwj
ㄅㄧㄠˋ qquld bezk bewj bif9 biwl
ㄅㄧㄢ qquoo bem bem bim bib
ㄅㄧㄢˇ qquoor bemj bemf bim8 bibj
ㄅㄧㄢˊ qquooe bemf bemd bim7 bibf
ㄅㄧㄢˋ qquood bemk bemj bim9 bibl
ㄅㄧㄣ qqup ben ben bin bin
ㄅㄧㄣˇ qqupr benj benf bin8 binj
ㄅㄧㄣˋ qqupd benk benj bin9 binl
ㄅㄧㄤˊ qqulle betf bekd bik7 bigf
ㄅㄧㄤˋ qqulld betk bekj bik9 bigl
ㄅㄧㄥ qqun bel bel big bim
ㄅㄧㄥˇ qqunr belj belf big8 bimj
ㄅㄧㄥˋ qqund belk belj big9 biml
ㄅㄧˇ qqur bej bef bi8 bij
ㄅㄧˊ qque bef bed bi7 bif
ㄅㄧˋ qqud bek bej bi9 bil
ㄅㄨ qqj bx bx bu bu
ㄅㄨˇ qqjr bxj bxf bu8 buj
ㄅㄨˊ qqje bxf bxd bu7 buf
ㄅㄨˋ qqjd bxk bxj bu9 bul
ㄆㄚ quu pa py pa pa
ㄆㄚˇ quur paj pyf pa8 paj
ㄆㄚˊ quue paf pyd pa7 paf
ㄆㄚˋ quud pak pyj pa9 pal
ㄆㄚ˙ quuy pad pys pa0 pad
ㄆㄛ qi po ph po po
ㄆㄛˇ qir poj phf po8 poj
ㄆㄛˊ qie pof phd po7 pof
ㄆㄛˋ qid pok phj po9 pol
ㄆㄞ qii pi pi py ph
ㄆㄞˇ qiir pij pif py8 phj
ㄆㄞˊ qiie pif pid py7 phf
ㄆㄞˋ qiid pik pij py9 phl
ㄆㄟ qo pq pa pt pk
ㄆㄟˇ qor pqj paf pt8 pkj
ㄆㄟˊ qoe pqf pad pt7 pkf
ㄆㄟˋ qod pqk paj pt9 pkl
ㄆㄠ ql pz pw pf pw
ㄆㄠˇ qlr pzj pwf pf8 pwj
ㄆㄠˊ qle pzf pwd pf7 pwf
ㄆㄠˋ qld pzk pwj pf9 pwl
ㄆㄡ qm pp po pw pv
ㄆㄡˇ qmr ppj pof pw8 pvj
ㄆㄡˊ qme ppf pod pw7 pvf
ㄆㄡˋ qmd ppk poj pw9 pvl
ㄆㄢ qoo pm pm pm pb
ㄆㄢˇ qoor pmj pmf pm8 pbj
ㄆㄢˊ qooe pmf pmd pm7 pbf
ㄆㄢˋ qood pmk pmj pm9 pbl
ㄆㄣ qp pn pn pn pn
ㄆㄣˇ qpr pnj pnf pn8 pnj
ㄆㄣˊ qpe pnf pnd pn7 pnf
ㄆㄣˋ qpd pnk pnj pn9 pnl
ㄆㄤ qll pt pk pk pg
ㄆㄤˇ qllr ptj pkf pk8 pgj
ㄆㄤˊ qlle ptf pkd pk7 pgf
ㄆㄤˋ qlld ptk pkj pk9 pgl
ㄆㄥ qn pl pl pg pm
ㄆㄥˇ qnr plj plf pg8 pmj
ㄆㄥˊ qne plf pld pg7 pmf
ㄆㄥˋ qnd plk plj pg9 pml
ㄆㄧ qu pe pe pi pi
ㄆㄧㄚ quuu pea pey pia pia
ㄆㄧㄝ qub pew pee pie pic
ㄆㄧㄝˇ qubr pewj peef pie8 picj
ㄆㄧㄝˋ qubd pewk peej pie9 picl
ㄆㄧㄠ qul pez pew pif piw
ㄆㄧㄠˇ qulr pezj pewf pif8 piwj
ㄆㄧㄠˊ qule pezf pewd pif7 piwf
ㄆㄧㄠˋ quld pezk pewj pif9 piwl
ㄆㄧㄢ quoo pem pem pim pib
ㄆㄧㄢˇ quoor pemj pemf pim8 pibj
ㄆㄧㄢˊ quooe pemf pemd pim7 pibf
ㄆㄧㄢˋ quood pemk pemj pim9 pibl
ㄆㄧㄣ qup pen pen pin pin
ㄆㄧㄣˇ qupr penj penf pin8 pinj
ㄆㄧㄣˊ qupe penf pend pin7 pinf
ㄆㄧㄣˋ qupd penk penj pin9 pinl
ㄆㄧㄥ qun pel pel pig pim
ㄆㄧㄥˇ qunr pelj pelf pig8 pimj
ㄆㄧㄥˊ qune pelf peld pig7 pimf
ㄆㄧㄥˋ qund pelk pelj pig9 piml
ㄆㄧˇ qur pej pef pi8 pij
ㄆㄧˊ que pef ped pi7 pif
ㄆㄧˋ qud pek pej pi9 pil
ㄆㄨ qj px px pu pu
ㄆㄨˇ qjr pxj pxf pu8 puj
ㄆㄨˊ qje pxf pxd pu7 puf
ㄆㄨˋ qjd pxk pxj pu9 pul
ㄇㄚ auu ma my ma ma
ㄇㄚˇ auur maj myf ma8 maj
ㄇㄚˊ auue maf myd ma7 maf
ㄇㄚˋ auud mak myj ma9 mal
ㄇㄚ˙ auuy mad mys ma0 mad
ㄇㄛ ai mo mh mo mo
ㄇㄛˇ air moj mhf mo8 moj
ㄇㄛˊ aie mof mhd mo7 mof
ㄇㄛˋ aid mok mhj mo9 mol
ㄇㄛ˙ aiy mod mhs mo0 mod
ㄇㄜ ak mr mg me me
ㄇㄜˋ akd mrk mgj me9 mel
ㄇㄜ˙ aky mrd mgs me0 med
ㄇㄞ aii mi mi my mh
ㄇㄞˇ aiir mij mif my8 mhj
ㄇㄞˊ aiie mif mid my7 mhf
ㄇㄞˋ aiid mik mij my9 mhl
ㄇㄟˇ aor mqj maf mt8 mkj
ㄇㄟˊ aoe mqf mad mt7 mkf
ㄇㄟˋ aod mqk maj mt9 mkl
ㄇㄠ al mz mw mf mw
ㄇㄠˇ alr mzj mwf mf8 mwj
ㄇㄠˊ ale mzf mwd mf7 mwf
ㄇㄠˋ ald mzk mwj mf9 mwl
ㄇㄡˇ amr mpj mof mw8 mvj
ㄇㄡˊ ame mpf mod mw7 mvf
ㄇㄡˋ amd mpk moj mw9 mvl
ㄇㄢ aoo mm mm mm mb
ㄇㄢˇ aoor mmj mmf mm8 mbj
ㄇㄢˊ aooe mmf mmd mm7 mbf
ㄇㄢˋ aood mmk mmj mm9 mbl
ㄇㄣ ap mn mn mn mn
ㄇㄣˇ apr mnj mnf mn8 mnj
ㄇㄣˊ ape mnf mnd mn7 mnf
ㄇㄣˋ apd mnk mnj mn9 mnl
ㄇㄣ˙ apy mnd mns mn0 mnd
ㄇㄤ all mt mk mk mg
ㄇㄤˇ allr mtj mkf mk8 mgj
ㄇㄤˊ alle mtf mkd mk7 mgf
ㄇㄤˋ alld mtk mkj mk9 mgl
ㄇㄥ an ml ml mg mm
ㄇㄥˇ anr mlj mlf mg8 mmj
ㄇㄥˊ ane mlf mld mg7 mmf
ㄇㄥˋ and mlk mlj mg9 mml
ㄇㄧ au me me mi mi
ㄇㄧㄝ aub mew mee mie mic
ㄇㄧㄝˊ aube mewf meed mie7 micf
ㄇㄧㄝˋ aubd mewk meej mie9 micl
ㄇㄧㄠ aul mez mew mif miw
ㄇㄧㄠˇ aulr mezj mewf mif8 miwj
ㄇㄧㄠˊ aule mezf mewd mif7 miwf
ㄇㄧㄠˋ auld mezk mewj mif9 miwl
ㄇㄧㄡˇ aumr mepj meof miw8 mivj
ㄇㄧㄡˊ aume mepf meod miw7 mivf
ㄇㄧㄡˋ aumd mepk meoj miw9 mivl
ㄇㄧㄢ auoo mem mem mim mib
ㄇㄧㄢˇ auoor memj memf mim8 mibj
ㄇㄧㄢˊ auooe memf memd mim7 mibf
ㄇㄧㄢˋ auood memk memj mim9 mibl
ㄇㄧㄣ aup men men min min
ㄇㄧㄣˇ aupr menj menf min8 minj
ㄇㄧㄣˊ aupe menf mend min7 minf
ㄇㄧㄥˇ aunr melj melf mig8 mimj
ㄇㄧㄥˊ aune melf meld mig7 mimf
ㄇㄧㄥˋ aund melk melj mig9 miml
ㄇㄧˇ aur mej mef mi8 mij
ㄇㄧˊ aue mef med mi7 mif
ㄇㄧˋ aud mek mej mi9 mil
ㄇㄨˇ ajr mxj mxf mu8 muj
ㄇㄨˊ aje mxf mxd mu7 muf
ㄇㄨˋ ajd mxk mxj mu9 mul
ㄈㄚ zuu fa fy fa fa
ㄈㄚˇ zuur faj fyf fa8 faj
ㄈㄚˊ zuue faf fyd fa7 faf
ㄈㄚˋ zuud fak fyj fa9 fal
ㄈㄛˊ zie fof fhd fo7 fof
ㄈㄟ zo fq fa ft fk
ㄈㄟˇ zor fqj faf ft8 fkj
ㄈㄟˊ zoe fqf fad ft7 fkf
ㄈㄟˋ zod fqk faj ft9 fkl
ㄈㄡ zm fp fo fw fv
ㄈㄡˇ zmr fpj fof fw8 fvj
ㄈㄡˊ zme fpf fod fw7 fvf
ㄈㄡˋ zmd fpk foj fw9 fvl
ㄈㄢ zoo fm fm fm fb
ㄈㄢˇ zoor fmj fmf fm8 fbj
ㄈㄢˊ zooe fmf fmd fm7 fbf
ㄈㄢˋ zood fmk fmj fm9 fbl
ㄈㄣ zp fn fn fn fn
ㄈㄣˇ zpr fnj fnf fn8 fnj
ㄈㄣˊ zpe fnf fnd fn7 fnf
ㄈㄣˋ zpd fnk fnj fn9 fnl
ㄈㄣ˙ zpy fnd fns fn0 fnd
ㄈㄤ zll ft fk fk fg
ㄈㄤˇ zllr ftj fkf fk8 fgj
ㄈㄤˊ zlle ftf fkd fk7 fgf
ㄈㄤˋ zlld ftk fkj fk9 fgl
ㄈㄥ zn fl fl fg fm
ㄈㄥˇ znr flj flf fg8 fmj
ㄈㄥˊ zne flf fld fg7 fmf
ㄈㄥˋ znd flk flj fg9 fml
ㄈㄧㄠˋ zuld fezk fewj fif9 fiwl
ㄈㄨ zj fx fx fu fu
ㄈㄨˇ zjr fxj fxf fu8 fuj
ㄈㄨˊ zje fxf fxd fu7 fuf
ㄈㄨˋ zjd fxk fxj fu9 ful
ㄉㄚ wwuu da dy da da
ㄉㄚˇ wwuur daj dyf da8 daj
ㄉㄚˊ wwuue daf dyd da7 daf
ㄉㄚˋ wwuud dak dyj da9 dal
ㄉㄚ˙ wwuuy dad dys da0 dad
ㄉㄜ wwk dr dg de de
ㄉㄜˊ wwke drf dgd de7 def
ㄉㄜ˙ wwky drd dgs de0 ded
ㄉㄞ wwii di di dy dh
ㄉㄞˇ wwiir dij dif dy8 dhj
ㄉㄞˋ wwiid dik dij dy9 dhl
ㄉㄟˇ wwor dqj daf dt8 dkj
ㄉㄠ wwl dz dw df dw
ㄉㄠˇ wwlr dzj dwf df8 dwj
ㄉㄠˊ wwle dzf dwd df7 dwf
ㄉㄠˋ wwld dzk dwj df9 dwl
ㄉㄡ wwm dp do dw dv
ㄉㄡˇ wwmr dpj dof dw8 dvj
ㄉㄡˊ wwme dpf dod dw7 dvf
ㄉㄡˋ wwmd dpk doj dw9 dvl
ㄉㄢ wwoo dm dm dm db
ㄉㄢˇ wwoor dmj dmf dm8 dbj
ㄉㄢˋ wwood dmk dmj dm9 dbl
ㄉㄣˋ wwpd dnk dnj dn9 dnl
ㄉㄤ wwll dt dk dk dg
ㄉㄤˇ wwllr dtj dkf dk8 dgj
ㄉㄤˋ wwlld dtk dkj dk9 dgl
ㄉㄥ wwn dl dl dg dm
ㄉㄥˇ wwnr dlj dlf dg8 dmj
ㄉㄥˋ wwnd dlk dlj dg9 dml
ㄉㄧ wwu de de di di
ㄉㄧㄚˇ wwuuur deaj deyf dia8 diaj
ㄉㄧㄝ wwub dew dee die dic
ㄉㄧㄝˇ wwubr dewj deef die8 dicj
ㄉㄧㄝˊ wwube dewf deed die7 dicf
ㄉㄧㄝˋ wwubd dewk deej die9 dicl
ㄉㄧㄠ wwul dez dew dif diw
ㄉㄧㄠˇ wwulr dezj dewf dif8 diwj
ㄉㄧㄠˋ wwuld dezk dewj dif9 diwl
ㄉㄧㄡ wwum dep deo diw div
ㄉㄧㄢ wwuoo dem dem dim dib
ㄉㄧㄢˇ wwuoor demj demf dim8 dibj
ㄉㄧㄢˊ wwuooe demf demd dim7 dibf
ㄉㄧㄢˋ wwuood demk demj dim9 dibl
ㄉㄧㄥ wwun del del dig dim
ㄉㄧㄥˇ wwunr delj delf dig8 dimj
ㄉㄧㄥˊ wwune delf deld dig7 dimf
ㄉㄧㄥˋ wwund delk delj dig9 diml
ㄉㄧˇ wwur dej def di8 dij
ㄉㄧˊ wwue def ded di7 dif
ㄉㄧˋ wwud dek dej di9 dil
ㄉㄨ wwj dx dx du du
ㄉㄨㄛ wwji dxo dxh duo duo
ㄉㄨㄛˇ wwjir dxoj dxhf duo8 duoj
ㄉㄨㄛˊ wwjie dxof dxhd duo7 duof
ㄉㄨㄛˋ wwjid dxok dxhj duo9 duol
ㄉㄨㄛ˙ wwjiy dxod dxhs duo0 duod
ㄉㄨㄟ wwjo dxq dxa dut duk
ㄉㄨㄟˇ wwjor dxqj dxaf dut8 dukj
ㄉㄨㄟˋ wwjod dxqk dxaj dut9 dukl
ㄉㄨㄢ wwjoo dxm dxm dum dub
ㄉㄨㄢˇ wwjoor dxmj dxmf dum8 dubj
ㄉㄨㄢˋ wwjood dxmk dxmj dum9 dubl
ㄉㄨㄣ wwjp dxn dxn dun dun
ㄉㄨㄣˇ wwjpr dxnj dxnf dun8 dunj
ㄉㄨㄣˋ wwjpd dxnk dxnj dun9 dunl
ㄉㄨㄤ wwjll dxt dxk duk dug
ㄉㄨㄥ wwjn dxl dxl dug dum
ㄉㄨㄥˇ wwjnr dxlj dxlf dug8 dumj
ㄉㄨㄥˋ wwjnd dxlk dxlj dug9 duml
ㄉㄨˇ wwjr dxj dxf du8 duj
ㄉㄨˊ wwje dxf dxd du7 duf
ㄉㄨˋ wwjd dxk dxj du9 dul
ㄊㄚ wuu ta ty ta ta
ㄊㄚˇ wuur taj tyf ta8 taj
ㄊㄚˋ wuud tak tyj ta9 tal
ㄊㄜˋ wkd trk tgj te9 tel
ㄊㄞ wii ti ti ty th
ㄊㄞˇ wiir tij tif ty8 thj
ㄊㄞˊ wiie tif tid ty7 thf
ㄊㄞˋ wiid tik tij ty9 thl
ㄊㄞ˙ wiiy tid tis ty0 thd
ㄊㄠ wl tz tw tf tw
ㄊㄠˇ wlr tzj twf tf8 twj
ㄊㄠˊ wle tzf twd tf7 twf
ㄊㄠˋ wld tzk twj tf9 twl
ㄊㄠ˙ wly tzd tws tf0 twd
ㄊㄡ wm tp to tw tv
ㄊㄡˇ wmr tpj tof tw8 tvj
ㄊㄡˊ wme tpf tod tw7 tvf
ㄊㄡˋ wmd tpk toj tw9 tvl
ㄊㄡ˙ wmy tpd tos tw0 tvd
ㄊㄢ woo tm tm tm tb
ㄊㄢˇ woor tmj tmf tm8 tbj
ㄊㄢˊ wooe tmf tmd tm7 tbf
ㄊㄢˋ wood tmk tmj tm9 tbl
ㄊㄤ wll tt tk tk tg
ㄊㄤˇ wllr ttj tkf tk8 tgj
ㄊㄤˊ wlle ttf tkd tk7 tgf
ㄊㄤˋ wlld ttk tkj tk9 tgl
ㄊㄥ wn tl tl tg tm
ㄊㄥˊ wne tlf tld tg7 tmf
ㄊㄥˋ wnd tlk tlj tg9 tml
ㄊㄧ wu te te ti ti
ㄊㄧㄝ wub tew tee tie tic
ㄊㄧㄝˇ wubr tewj teef tie8 ticj
ㄊㄧㄝˊ wube tewf teed tie7 ticf
ㄊㄧㄝˋ wubd tewk teej tie9 ticl
ㄊㄧㄠ wul tez tew tif tiw
ㄊㄧㄠˇ wulr tezj tewf tif8 tiwj
ㄊㄧㄠˊ wule tezf tewd tif7 tiwf
ㄊㄧㄠˋ wuld tezk tewj tif9 tiwl
ㄊㄧㄢ wuoo tem tem tim tib
ㄊㄧㄢˇ wuoor temj temf tim8 tibj
ㄊㄧㄢˊ wuooe temf temd tim7 tibf
ㄊㄧㄢˋ wuood temk temj tim9 tibl
ㄊㄧㄥ wun tel tel tig tim
ㄊㄧㄥˇ wunr telj telf tig8 timj
ㄊㄧㄥˊ wune telf teld tig7 timf
ㄊㄧㄥˋ wund telk telj tig9 timl
ㄊㄧˇ wur tej tef ti8 tij
ㄊㄧˊ wue tef ted ti7 tif
ㄊㄧˋ wud tek tej ti9 til
ㄊㄨ wj tx tx tu tu
ㄊㄨㄛ wji txo txh tuo tuo
ㄊㄨㄛˇ wjir txoj txhf tuo8 tuoj
ㄊㄨㄛˊ wjie txof txhd tuo7 tuof
ㄊㄨㄛˋ wjid txok txhj tuo9 tuol
ㄊㄨㄟ wjo txq txa tut tuk
ㄊㄨㄟˇ wjor txqj txaf tut8 tukj
ㄊㄨㄟˊ wjoe txqf txad tut7 tukf
ㄊㄨㄟˋ wjod txqk txaj tut9 tukl
ㄊㄨㄢ wjoo txm txm tum tub
ㄊㄨㄢˇ wjoor txmj txmf tum8 tubj
ㄊㄨㄢˊ wjooe txmf txmd tum7 tubf
ㄊㄨㄢˋ wjood txmk txmj tum9 tubl
ㄊㄨㄣ wjp txn txn tun tun
ㄊㄨㄣˇ wjpr txnj txnf tun8 tunj
ㄊㄨㄣˊ wjpe txnf txnd tun7 tunf
ㄊㄨㄣˋ wjpd txnk txnj tun9 tunl
ㄊㄨㄥ wjn txl txl tug tum
ㄊㄨㄥˇ wjnr txlj txlf tug8 tumj
ㄊㄨㄥˊ wjne txlf txld tug7 tumf
ㄊㄨㄥˋ wjnd txlk txlj tug9 tuml
ㄊㄨˇ wjr txj txf tu8 tuj
ㄊㄨˊ wje txf txd tu7 tuf
ㄊㄨˋ wjd txk txj tu9 tul
ㄋㄚ suu na ny na na
ㄋㄚˇ suur naj nyf na8 naj
ㄋㄚˊ suue naf nyd na7 naf
ㄋㄚˋ suud nak nyj na9 nal
ㄋㄚ˙ suuy nad nys na0 nad
ㄋㄜˋ skd nrk ngj ne9 nel
ㄋㄜ˙ sky nrd ngs ne0 ned
ㄋㄞˇ siir nij nif ny8 nhj
ㄋㄞˊ siie nif nid ny7 nhf
ㄋㄞˋ siid nik nij ny9 nhl
ㄋㄟˇ sor nqj naf nt8 nkj
ㄋㄟˊ soe nqf nad nt7 nkf
ㄋㄟˋ sod nqk naj nt9 nkl
ㄋㄠ sl nz nw nf nw
ㄋㄠˇ slr nzj nwf nf8 nwj
ㄋㄠˊ sle nzf nwd nf7 nwf
ㄋㄠˋ sld nzk nwj nf9 nwl
ㄋㄡˇ smr npj nof nw8 nvj
ㄋㄡˊ sme npf nod nw7 nvf
ㄋㄡˋ smd npk noj nw9 nvl
ㄋㄢ soo nm nm nm nb
ㄋㄢˇ soor nmj nmf nm8 nbj
ㄋㄢˊ sooe nmf nmd nm7 nbf
ㄋㄢˋ sood nmk nmj nm9 nbl
ㄋㄣˇ spr nnj nnf nn8 nnj
ㄋㄣˋ spd nnk nnj nn9 nnl
ㄋㄤ sll nt nk nk ng
ㄋㄤˇ sllr ntj nkf nk8 ngj
ㄋㄤˊ slle ntf nkd nk7 ngf
ㄋㄤˋ slld ntk nkj nk9 ngl
ㄋㄤ˙ slly ntd nks nk0 ngd
ㄋㄥˇ snr nlj nlf ng8 nmj
ㄋㄥˊ sne nlf nld ng7 nmf
ㄋㄧ su ne ne ni ni
ㄋㄧㄝ sub new nee nie nic
ㄋㄧㄝˊ sube newf need nie7 nicf
ㄋㄧㄝˋ subd newk neej nie9 nicl
ㄋㄧㄠˇ sulr nezj newf nif8 niwj
ㄋㄧㄠˋ suld nezk newj nif9 niwl
ㄋㄧㄡ sum nep neo niw niv
ㄋㄧㄡˇ sumr nepj neof niw8 nivj
ㄋㄧㄡˊ sume nepf neod niw7 nivf
ㄋㄧㄡˋ sumd nepk neoj niw9 nivl
ㄋㄧㄢ suoo nem nem nim nib
ㄋㄧㄢˇ suoor nemj nemf nim8 nibj
ㄋㄧㄢˊ suooe nemf nemd nim7 nibf
ㄋㄧㄢˋ suood nemk nemj nim9 nibl
ㄋㄧㄣ sup nen nen nin nin
ㄋㄧㄣˇ supr nenj nenf nin8 ninj
ㄋㄧㄣˊ supe nenf nend nin7 ninf
ㄋㄧㄣˋ supd nenk nenj nin9 ninl
ㄋㄧㄤˇ sullr netj nekf nik8 nigj
ㄋㄧㄤˊ sulle netf nekd nik7 nigf
ㄋㄧㄤˋ sulld netk nekj nik9 nigl
ㄋㄧㄥˇ sunr nelj nelf nig8 nimj
ㄋㄧㄥˊ sune nelf neld nig7 nimf
ㄋㄧㄥˋ sund nelk nelj nig9 niml
ㄋㄧˇ sur nej nef ni8 nij
ㄋㄧˊ sue nef ned ni7 nif
ㄋㄧˋ sud nek nej ni9 nil
ㄋㄨㄛˇ sjir nxoj nxhf nuo8 nuoj
ㄋㄨㄛˊ sjie nxof nxhd nuo7 nuof
ㄋㄨㄛˋ sjid nxok nxhj nuo9 nuol
ㄋㄨㄟˊ sjoe nxqf nxad nut7 nukf
ㄋㄨㄢˇ sjoor nxmj nxmf num8 nubj
ㄋㄨㄢˊ sjooe nxmf nxmd num7 nubf
ㄋㄨㄢˋ sjood nxmk nxmj num9 nubl
ㄋㄨㄣˊ sjpe nxnf nxnd nun7 nunf
ㄋㄨㄥˇ sjnr nxlj nxlf nug8 numj
ㄋㄨㄥˊ sjne nxlf nxld nug7 numf
ㄋㄨㄥˋ sjnd nxlk nxlj nug9 numl
ㄋㄨˇ sjr nxj nxf nu8 nuj
ㄋㄨˊ sje nxf nxd nu7 nuf
ㄋㄨˋ sjd nxk nxj nu9 nul
ㄋㄩㄝˋ smmbd nuwk nuej nve9 nycl
ㄋㄩˇ smmr nuj nuf nv8 nyj
ㄋㄩˊ smme nuf nud nv7 nyf
ㄋㄩˋ smmd nuk nuj nv9 nyl
ㄌㄚ xuu la ly la la
ㄌㄚˇ xuur laj lyf la8 laj
ㄌㄚˊ xuue laf lyd la7 laf
ㄌㄚˋ xuud lak lyj la9 lal
ㄌㄚ˙ xuuy lad lys la0 lad
ㄌㄛ xi lo lh lo lo
ㄌㄛ˙ xiy lod lhs lo0 lod
ㄌㄜ xk lr lg le le
ㄌㄜˊ xke lrf lgd le7 lef
ㄌㄜˋ xkd lrk lgj le9 lel
ㄌㄜ˙ xky lrd lgs le0 led
ㄌㄞˇ xiir lij lif ly8 lhj
ㄌㄞˊ xiie lif lid ly7 lhf
ㄌㄞˋ xiid lik lij ly9 lhl
ㄌㄟ xo lq la lt lk
ㄌㄟˇ xor lqj laf lt8 lkj
ㄌㄟˊ xoe lqf lad lt7 lkf
ㄌㄟˋ xod lqk laj lt9 lkl
ㄌㄟ˙ xoy lqd las lt0 lkd
ㄌㄠ xl lz lw lf lw
ㄌㄠˇ xlr lzj lwf lf8 lwj
ㄌㄠˊ xle lzf lwd lf7 lwf
ㄌㄠˋ xld lzk lwj lf9 lwl
ㄌㄡ xm lp lo lw lv
ㄌㄡˇ xmr lpj lof lw8 lvj
ㄌㄡˊ xme lpf lod lw7 lvf
ㄌㄡˋ xmd lpk loj lw9 lvl
ㄌㄡ˙ xmy lpd los lw0 lvd
ㄌㄢˇ xoor lmj lmf lm8 lbj
ㄌㄢˊ xooe lmf lmd lm7 lbf
ㄌㄢˋ xood lmk lmj lm9 lbl
ㄌㄤ xll lt lk lk lg
ㄌㄤˇ xllr ltj lkf lk8 lgj
ㄌㄤˊ xlle ltf lkd lk7 lgf
ㄌㄤˋ xlld ltk lkj lk9 lgl
ㄌㄥ xn ll ll lg lm
ㄌㄥˇ xnr llj llf lg8 lmj
ㄌㄥˊ xne llf lld lg7 lmf
ㄌㄥˋ xnd llk llj lg9 lml
ㄌㄧ xu le le li li
ㄌㄧㄚˇ xuuur leaj leyf lia8 liaj
ㄌㄧㄝ xub lew lee lie lic
ㄌㄧㄝˇ xubr lewj leef lie8 licj
ㄌㄧㄝˊ xube lewf leed lie7 licf
ㄌㄧㄝˋ xubd lewk leej lie9 licl
ㄌㄧㄠ xul lez lew lif liw
ㄌㄧㄠˇ xulr lezj lewf lif8 liwj
ㄌㄧㄠˊ xule lezf lewd lif7 liwf
ㄌㄧㄠˋ xuld lezk lewj lif9 liwl
ㄌㄧㄡ xum lep leo liw liv
ㄌㄧㄡˇ xumr lepj leof liw8 livj
ㄌㄧㄡˊ xume lepf leod liw7 livf
ㄌㄧㄡˋ xumd lepk leoj liw9 livl
ㄌㄧㄢ xuoo lem lem lim lib
ㄌㄧㄢˇ xuoor lemj lemf lim8 libj
ㄌㄧㄢˊ xuooe lemf lemd lim7 libf
ㄌㄧㄢˋ xuood lemk lemj lim9 libl
ㄌㄧㄣˇ xupr lenj lenf lin8 linj
ㄌㄧㄣˊ xupe lenf lend lin7 linf
ㄌㄧㄣˋ xupd lenk lenj lin9 linl
ㄌㄧㄤˇ xullr letj lekf lik8 ligj
ㄌㄧㄤˊ xulle letf lekd lik7 ligf
ㄌㄧㄤˋ xulld letk lekj lik9 ligl
ㄌㄧㄥ xun lel lel lig lim
ㄌㄧㄥˇ xunr lelj lelf lig8 limj
ㄌㄧㄥˊ xune lelf leld lig7 limf
ㄌㄧㄥˋ xund lelk lelj lig9 liml
ㄌㄧˇ xur lej lef li8 lij
ㄌㄧˊ xue lef led li7 lif
ㄌㄧˋ xud lek lej li9 lil
ㄌㄧ˙ xuy led les li0 lid
ㄌㄨ xj lx lx lu lu
ㄌㄨㄛ xji lxo lxh luo luo
ㄌㄨㄛˇ xjir lxoj lxhf luo8 luoj
ㄌㄨㄛˊ xjie lxof lxhd luo7 luof
ㄌㄨㄛˋ xjid lxok lxhj luo9 luol
ㄌㄨㄛ˙ xjiy lxod lxhs luo0 luod
ㄌㄨㄢˇ xjoor lxmj lxmf lum8 lubj
ㄌㄨㄢˊ xjooe lxmf lxmd lum7 lubf
ㄌㄨㄢˋ xjood lxmk lxmj lum9 lubl
ㄌㄨㄣ xjp lxn lxn lun lun
ㄌㄨㄣˇ xjpr lxnj lxnf lun8 lunj
ㄌㄨㄣˊ xjpe lxnf lxnd lun7 lunf
ㄌㄨㄣˋ xjpd lxnk lxnj lun9 lunl
ㄌㄨㄥ xjn lxl lxl lug lum
ㄌㄨㄥˇ xjnr lxlj lxlf lug8 lumj
ㄌㄨㄥˊ xjne lxlf lxld lug7 lumf
ㄌㄨㄥˋ xjnd lxlk lxlj lug9 luml
ㄌㄨˇ xjr lxj lxf lu8 luj
ㄌㄨˊ xje lxf lxd lu7 luf
ㄌㄨˋ xjd lxk lxj lu9 lul
ㄌㄩ xmm lu lu lv ly
ㄌㄩㄝ xmmb luw lue lve lyc
ㄌㄩㄝˇ xmmbr luwj luef lve8 lycj
ㄌㄩㄝˋ xmmbd luwk luej lve9 lycl
ㄌㄩㄢˇ xmmoor lumj lumf lvm8 lybj
ㄌㄩㄢˊ xmmooe lumf lumd lvm7 lybf
ㄌㄩˇ xmmr luj luf lv8 lyj
ㄌㄩˊ xmme luf lud lv7 lyf
ㄌㄩˋ xmmd luk luj lv9 lyl
ㄍㄚ euu va gy ga ga
ㄍㄚˇ euur vaj gyf ga8 gaj
ㄍㄚˊ euue vaf gyd ga7 gaf
ㄍㄚˋ euud vak gyj ga9 gal
ㄍㄚ˙ euuy vad gys ga0 gad
ㄍㄜ ek vr gg ge ge
ㄍㄜˇ ekr vrj ggf ge8 gej
ㄍㄜˊ eke vrf ggd ge7 gef
ㄍㄜˋ ekd vrk ggj ge9 gel
ㄍㄜ˙ eky vrd ggs ge0 ged
ㄍㄞ eii vi gi gy gh
ㄍㄞˇ eiir vij gif gy8 ghj
ㄍㄞˋ eiid vik gij gy9 ghl
ㄍㄟˇ eor vqj gaf gt8 gkj
ㄍㄠ el vz gw gf gw
ㄍㄠˇ elr vzj gwf gf8 gwj
ㄍㄠˋ eld vzk gwj gf9 gwl
ㄍㄡ em vp go gw gv
ㄍㄡˇ emr vpj gof gw8 gvj
ㄍㄡˋ emd vpk goj gw9 gvl
ㄍㄢ eoo vm gm gm gb
ㄍㄢˇ eoor vmj gmf gm8 gbj
ㄍㄢˋ eood vmk gmj gm9 gbl
ㄍㄣ ep vn gn gn gn
ㄍㄣˇ epr vnj gnf gn8 gnj
ㄍㄣˊ epe vnf gnd gn7 gnf
ㄍㄣˋ epd vnk gnj gn9 gnl
ㄍㄤ ell vt gk gk gg
ㄍㄤˇ ellr vtj gkf gk8 ggj
ㄍㄤˋ elld vtk gkj gk9 ggl
ㄍㄥ en vl gl gg gm
ㄍㄥˇ enr vlj glf gg8 gmj
ㄍㄥˋ end vlk glj gg9 gml
ㄍㄧㄠˊ eule `vezf gewd gif7 giwf
ㄍㄧㄣ eup `ven gen gin gin
ㄍㄨ ej vx gx gu gu
ㄍㄨㄚ eju vxa gxy gua gua
ㄍㄨㄚˇ ejur vxaj gxyf gua8 guaj
ㄍㄨㄚˊ ejue vxaf gxyd gua7 guaf
ㄍㄨㄚˋ ejud vxak gxyj gua9 gual
ㄍㄨㄛ eji vxo gxh guo guo
ㄍㄨㄛˇ ejir vxoj gxhf guo8 guoj
ㄍㄨㄛˊ ejie vxof gxhd guo7 guof
ㄍㄨㄛˋ ejid vxok gxhj guo9 guol
ㄍㄨㄞ ejii vxi gxi guy guh
ㄍㄨㄞˇ ejiir vxij gxif guy8 guhj
ㄍㄨㄞˋ ejiid vxik gxij guy9 guhl
ㄍㄨㄟ ejo vxq gxa gut guk
ㄍㄨㄟˇ ejor vxqj gxaf gut8 gukj
ㄍㄨㄟˋ ejod vxqk gxaj gut9 gukl
ㄍㄨㄢ ejoo vxm gxm gum gub
ㄍㄨㄢˇ ejoor vxmj gxmf gum8 gubj
ㄍㄨㄢˋ ejood vxmk gxmj gum9 gubl
ㄍㄨㄣ ejp vxn gxn gun gun
ㄍㄨㄣˇ ejpr vxnj gxnf gun8 gunj
ㄍㄨㄣˋ ejpd vxnk gxnj gun9 gunl
ㄍㄨㄤ ejll vxt gxk guk gug
ㄍㄨㄤˇ ejllr vxtj gxkf guk8 gugj
ㄍㄨㄤˋ ejlld vxtk gxkj guk9 gugl
ㄍㄨㄥ ejn vxl gxl gug gum
ㄍㄨㄥˇ ejnr vxlj gxlf gug8 gumj
ㄍㄨㄥˊ ejne vxlf gxld gug7 gumf
ㄍㄨㄥˋ ejnd vxlk gxlj gug9 guml
ㄍㄨˇ ejr vxj gxf gu8 guj
ㄍㄨˊ eje vxf gxd gu7 guf
ㄍㄨˋ ejd vxk gxj gu9 gul
ㄎㄚ duu ka ky ka ka
ㄎㄚˇ duur kaj kyf ka8 kaj
ㄎㄚˋ duud kak kyj ka9 kal
ㄎㄜ dk kr kg ke ke
ㄎㄜˇ dkr krj kgf ke8 kej
ㄎㄜˊ dke krf kgd ke7 kef
ㄎㄜˋ dkd krk kgj ke9 kel
ㄎㄞ dii ki ki ky kh
ㄎㄞˇ diir kij kif ky8 khj
ㄎㄞˋ diid kik kij ky9 khl
ㄎㄠ dl kz kw kf kw
ㄎㄠˇ dlr kzj kwf kf8 kwj
ㄎㄠˋ dld kzk kwj kf9 kwl
ㄎㄡ dm kp ko kw kv
ㄎㄡˇ dmr kpj kof kw8 kvj
ㄎㄡˋ dmd kpk koj kw9 kvl
ㄎㄢ doo km km km kb
ㄎㄢˇ door kmj kmf km8 kbj
ㄎㄢˋ dood kmk kmj km9 kbl
ㄎㄣ dp kn kn kn kn
ㄎㄣˇ dpr knj knf kn8 knj
ㄎㄣˋ dpd knk knj kn9 knl
ㄎㄤ dll kt kk kk kg
ㄎㄤˇ dllr ktj kkf kk8 kgj
ㄎㄤˊ dlle ktf kkd kk7 kgf
ㄎㄤˋ dlld ktk kkj kk9 kgl
ㄎㄥ dn kl kl kg km
ㄎㄥˇ dnr klj klf kg8 kmj
ㄎㄧㄤ dull ket kek kik kig
ㄎㄨ dj kx kx ku ku
ㄎㄨㄚ dju kxa kxy kua kua
ㄎㄨㄚˇ djur kxaj kxyf kua8 kuaj
ㄎㄨㄚˋ djud kxak kxyj kua9 kual
ㄎㄨㄛˋ djid kxok kxhj kuo9 kuol
ㄎㄨㄞ djii kxi kxi kuy kuh
ㄎㄨㄞˇ djiir kxij kxif kuy8 kuhj
ㄎㄨㄞˋ djiid kxik kxij kuy9 kuhl
ㄎㄨㄟ djo kxq kxa kut kuk
ㄎㄨㄟˇ djor kxqj kxaf kut8 kukj
ㄎㄨㄟˊ djoe kxqf kxad kut7 kukf
ㄎㄨㄟˋ djod kxqk kxaj kut9 kukl
ㄎㄨㄢ djoo kxm kxm kum kub
ㄎㄨㄢˇ djoor kxmj kxmf kum8 kubj
ㄎㄨㄢˋ djood kxmk kxmj kum9 kubl
ㄎㄨㄣ djp kxn kxn kun kun
ㄎㄨㄣˇ djpr kxnj kxnf kun8 kunj
ㄎㄨㄣˋ djpd kxnk kxnj kun9 kunl
ㄎㄨㄤ djll kxt kxk kuk kug
ㄎㄨㄤˇ djllr kxtj kxkf kuk8 kugj
ㄎㄨㄤˊ djlle kxtf kxkd kuk7 kugf
ㄎㄨㄤˋ djlld kxtk kxkj kuk9 kugl
ㄎㄨㄥ djn kxl kxl kug kum
ㄎㄨㄥˇ djnr kxlj kxlf kug8 kumj
ㄎㄨㄥˋ djnd kxlk kxlj kug9 kuml
ㄎㄨˇ djr kxj kxf ku8 kuj
ㄎㄨˊ dje kxf kxd ku7 kuf
ㄎㄨˋ djd kxk kxj ku9 kul
ㄏㄚ cuu ha hy ha ha
ㄏㄚˇ cuur haj hyf ha8 haj
ㄏㄚˊ cuue haf hyd ha7 haf
ㄏㄜ ck hr hg he he
ㄏㄜˇ ckr hrj hgf he8 hej
ㄏㄜˊ cke hrf hgd he7 hef
ㄏㄜˋ ckd hrk hgj he9 hel
ㄏㄞ cii hi hi hy hh
ㄏㄞˇ ciir hij hif hy8 hhj
ㄏㄞˊ ciie hif hid hy7 hhf
ㄏㄞˋ ciid hik hij hy9 hhl
ㄏㄟ co hq ha ht hk
ㄏㄟˇ cor hqj haf ht8 hkj
ㄏㄠ cl hz hw hf hw
ㄏㄠˇ clr hzj hwf hf8 hwj
ㄏㄠˊ cle hzf hwd hf7 hwf
ㄏㄠˋ cld hzk hwj hf9 hwl
ㄏㄡ cm hp ho hw hv
ㄏㄡˇ cmr hpj hof hw8 hvj
ㄏㄡˊ cme hpf hod hw7 hvf
ㄏㄡˋ cmd hpk hoj hw9 hvl
ㄏㄢ coo hm hm hm hb
ㄏㄢˇ coor hmj hmf hm8 hbj
ㄏㄢˊ cooe hmf hmd hm7 hbf
ㄏㄢˋ cood hmk hmj hm9 hbl
ㄏㄣ cp hn hn hn hn
ㄏㄣˇ cpr hnj hnf hn8 hnj
ㄏㄣˊ cpe hnf hnd hn7 hnf
ㄏㄣˋ cpd hnk hnj hn9 hnl
ㄏㄤ cll ht hk hk hg
ㄏㄤˇ cllr htj hkf hk8 hgj
ㄏㄤˊ clle htf hkd hk7 hgf
ㄏㄤˋ clld htk hkj hk9 hgl
ㄏㄥ cn hl hl hg hm
ㄏㄥˊ cne hlf hld hg7 hmf
ㄏㄥˋ cnd hlk hlj hg9 hml
ㄏㄨ cj hx hx hu hu
ㄏㄨㄚ cju hxa hxy hua hua
ㄏㄨㄚˇ cjur hxaj hxyf hua8 huaj
ㄏㄨㄚˊ cjue hxaf hxyd hua7 huaf
ㄏㄨㄚˋ cjud hxak hxyj hua9 hual
ㄏㄨㄛ cji hxo hxh huo huo
ㄏㄨㄛˇ cjir hxoj hxhf huo8 huoj
ㄏㄨㄛˊ cjie hxof hxhd huo7 huof
ㄏㄨㄛˋ cjid hxok hxhj huo9 huol
ㄏㄨㄛ˙ cjiy hxod hxhs huo0 huod
ㄏㄨㄞˊ cjiie hxif hxid huy7 huhf
ㄏㄨㄞˋ cjiid hxik hxij huy9 huhl
ㄏㄨㄟ cjo hxq hxa hut huk
ㄏㄨㄟˇ cjor hxqj hxaf hut8 hukj
ㄏㄨㄟˊ cjoe hxqf hxad hut7 hukf
ㄏㄨㄟˋ cjod hxqk hxaj hut9 hukl
ㄏㄨㄢ cjoo hxm hxm hum hub
ㄏㄨㄢˇ cjoor hxmj hxmf hum8 hubj
ㄏㄨㄢˊ cjooe hxmf hxmd hum7 hubf
ㄏㄨㄢˋ cjood hxmk hxmj hum9 hubl
ㄏㄨㄣ cjp hxn hxn hun hun
ㄏㄨㄣˇ cjpr hxnj hxnf hun8 hunj
ㄏㄨㄣˊ cjpe hxnf hxnd hun7 hunf
ㄏㄨㄣˋ cjpd hxnk hxnj hun9 hunl
ㄏㄨㄤ cjll hxt hxk huk hug
ㄏㄨㄤˇ cjllr hxtj hxkf huk8 hugj
ㄏㄨㄤˊ cjlle hxtf hxkd huk7 hugf
ㄏㄨㄤˋ cjlld hxtk hxkj huk9 hugl
ㄏㄨㄤ˙ cjlly hxtd hxks huk0 hugd
ㄏㄨㄥ cjn hxl hxl hug hum
ㄏㄨㄥˇ cjnr hxlj hxlf hug8 humj
ㄏㄨㄥˊ cjne hxlf hxld hug7 humf
ㄏㄨㄥˋ cjnd hxlk hxlj hug9 huml
ㄏㄨˇ cjr hxj hxf hu8 huj
ㄏㄨˊ cje hxf hxd hu7 huf
ㄏㄨˋ cjd hxk hxj hu9 hul
ㄐㄧ ru ge je ji ji
ㄐㄧㄚ ruuu gea jey jia jia
ㄐㄧㄚˇ ruuur geaj jeyf jia8 jiaj
ㄐㄧㄚˊ ruuue geaf jeyd jia7 jiaf
ㄐㄧㄚˋ ruuud geak jeyj jia9 jial
ㄐㄧㄝ rub gew jee jie jic
ㄐㄧㄝˇ rubr gewj jeef jie8 jicj
ㄐㄧㄝˊ rube gewf jeed jie7 jicf
ㄐㄧㄝˋ rubd gewk jeej jie9 jicl
ㄐㄧㄝ˙ ruby gewd jees jie0 jicd
ㄐㄧㄠ rul gez jew jif jiw
ㄐㄧㄠˇ rulr gezj jewf jif8 jiwj
ㄐㄧㄠˊ rule gezf jewd jif7 jiwf
ㄐㄧㄠˋ ruld gezk jewj jif9 jiwl
ㄐㄧㄡ rum gep jeo jiw jiv
ㄐㄧㄡˇ rumr gepj jeof jiw8 jivj
ㄐㄧㄡˋ rumd gepk jeoj jiw9 jivl
ㄐㄧㄢ ruoo gem jem jim jib
ㄐㄧㄢˇ ruoor gemj jemf jim8 jibj
ㄐㄧㄢˋ ruood gemk jemj jim9 jibl
ㄐㄧㄣ rup gen jen jin jin
ㄐㄧㄣˇ rupr genj jenf jin8 jinj
ㄐㄧㄣˋ rupd genk jenj jin9 jinl
ㄐㄧㄤ rull get jek jik jig
ㄐㄧㄤˇ rullr getj jekf jik8 jigj
ㄐㄧㄤˊ rulle getf jekd jik7 jigf
ㄐㄧㄤˋ rulld getk jekj jik9 jigl
ㄐㄧㄥ run gel jel jig jim
ㄐㄧㄥˇ runr gelj jelf jig8 jimj
ㄐㄧㄥˋ rund gelk jelj jig9 jiml
ㄐㄧˇ rur gej jef ji8 jij
ㄐㄧˊ rue gef jed ji7 jif
ㄐㄧˋ rud gek jej ji9 jil
ㄐㄩ rm gu ju jv jy
ㄐㄩㄝ rmb guw jue jve jyc
ㄐㄩㄝˇ rmbr guwj juef jve8 jycj
ㄐㄩㄝˊ rmbe guwf jued jve7 jycf
ㄐㄩㄝˋ rmbd guwk juej jve9 jycl
ㄐㄩㄢ rmoo gum jum jvm jyb
ㄐㄩㄢˇ rmoor gumj jumf jvm8 jybj
ㄐㄩㄢˋ rmood gumk jumj jvm9 jybl
ㄐㄩㄣ rmp gun jun jvn jyn
ㄐㄩㄣˇ rmpr gunj junf jvn8 jynj
ㄐㄩㄣˊ rmpe gunf jund jvn7 jynf
ㄐㄩㄣˋ rmpd gunk junj jvn9 jynl
ㄐㄩㄥ rmn gul jul jvg jym
ㄐㄩㄥˇ rmnr gulj julf jvg8 jymj
ㄐㄩㄥˋ rmnd gulk julj jvg9 jyml
ㄐㄩˇ rmr guj juf jv8 jyj
ㄐㄩˊ rme guf jud jv7 jyf
ㄐㄩˋ rmd guk juj jv9 jyl
ㄑㄧ fu ve ve qi qi
ㄑㄧㄚ fuuu vea vey qia qia
ㄑㄧㄚˇ fuuur veaj veyf qia8 qiaj
ㄑㄧㄚˊ fuuue veaf veyd qia7 qiaf
ㄑㄧㄚˋ fuuud veak veyj qia9 qial
ㄑㄧㄝ fub vew vee qie qic
ㄑㄧㄝˇ fubr vewj veef qie8 qicj
ㄑㄧㄝˊ fube vewf veed qie7 qicf
ㄑㄧㄝˋ fubd vewk veej qie9 qicl
ㄑㄧㄠ ful vez vew qif qiw
ㄑㄧㄠˇ fulr vezj vewf qif8 qiwj
ㄑㄧㄠˊ fule vezf vewd qif7 qiwf
ㄑㄧㄠˋ fuld vezk vewj qif9 qiwl
ㄑㄧㄡ fum vep veo qiw qiv
ㄑㄧㄡˇ fumr vepj veof qiw8 qivj
ㄑㄧㄡˊ fume vepf veod qiw7 qivf
ㄑㄧㄡˋ fumd vepk veoj qiw9 qivl
ㄑㄧㄢ fuoo vem vem qim qib
ㄑㄧㄢˇ fuoor vemj vemf qim8 qibj
ㄑㄧㄢˊ fuooe vemf vemd qim7 qibf
ㄑㄧㄢˋ fuood vemk vemj qim9 qibl
ㄑㄧㄣ fup ven ven qin qin
ㄑㄧㄣˇ fupr venj venf qin8 qinj
ㄑㄧㄣˊ fupe venf vend qin7 qinf
ㄑㄧㄣˋ fupd venk venj qin9 qinl
ㄑㄧㄤ full vet vek qik qig
ㄑㄧㄤˇ fullr vetj vekf qik8 qigj
ㄑㄧㄤˊ fulle vetf vekd qik7 qigf
ㄑㄧㄤˋ fulld vetk vekj qik9 qigl
ㄑㄧㄥ fun vel vel qig qim
ㄑㄧㄥˇ funr velj velf qig8 qimj
ㄑㄧㄥˊ fune velf veld qig7 qimf
ㄑㄧㄥˋ fund velk velj qig9 qiml
ㄑㄧˇ fur vej vef qi8 qij
ㄑㄧˊ fue vef ved qi7 qif
ㄑㄧˋ fud vek vej qi9 qil
ㄑㄩ fm vu vu qv qy
ㄑㄩㄝ fmb vuw vue qve qyc
ㄑㄩㄝˊ fmbe vuwf vued qve7 qycf
ㄑㄩㄝˋ fmbd vuwk vuej qve9 qycl
ㄑㄩㄢ fmoo vum vum qvm qyb
ㄑㄩㄢˇ fmoor vumj vumf qvm8 qybj
ㄑㄩㄢˊ fmooe vumf vumd qvm7 qybf
ㄑㄩㄢˋ fmood vumk vumj qvm9 qybl
ㄑㄩㄣ fmp vun vun qvn qyn
ㄑㄩㄣˇ fmpr vunj vunf qvn8 qynj
ㄑㄩㄣˊ fmpe vunf vund qvn7 qynf
ㄑㄩㄣˋ fmpd vunk vunj qvn9 qynl
ㄑㄩㄥ fmn vul vul qvg qym
ㄑㄩㄥˇ fmnr vulj vulf qvg8 qymj
ㄑㄩㄥˊ fmne vulf vuld qvg7 qymf
ㄑㄩㄥˋ fmnd vulk vulj qvg9 qyml
ㄑㄩˇ fmr vuj vuf qv8 qyj
ㄑㄩˊ fme vuf vud qv7 qyf
ㄑㄩˋ fmd vuk vuj qv9 qyl
ㄑ˙ fy vd vs `q0 `qd
ㄒㄧ vu ce ce xi xi
ㄒㄧㄚ vuuu cea cey xia xia
ㄒㄧㄚˇ vuuur ceaj ceyf xia8 xiaj
ㄒㄧㄚˊ vuuue ceaf ceyd xia7 xiaf
ㄒㄧㄚˋ vuuud ceak ceyj xia9 xial
ㄒㄧㄝ vub cew cee xie xic
ㄒㄧㄝˇ vubr cewj ceef xie8 xicj
ㄒㄧㄝˊ vube cewf ceed xie7 xicf
ㄒㄧㄝˋ vubd cewk ceej xie9 xicl
ㄒㄧㄠ vul cez cew xif xiw
ㄒㄧㄠˇ vulr cezj cewf xif8 xiwj
ㄒㄧㄠˊ vule cezf cewd xif7 xiwf
ㄒㄧㄠˋ vuld cezk cewj xif9 xiwl
ㄒㄧㄡ vum cep ceo xiw xiv
ㄒㄧㄡˇ vumr cepj ceof xiw8 xivj
ㄒㄧㄡˊ vume cepf ceod xiw7 xivf
ㄒㄧㄡˋ vumd cepk ceoj xiw9 xivl
ㄒㄧㄢ vuoo cem cem xim xib
ㄒㄧㄢˇ vuoor cemj cemf xim8 xibj
ㄒㄧㄢˊ vuooe cemf cemd xim7 xibf
ㄒㄧㄢˋ vuood cemk cemj xim9 xibl
ㄒㄧㄣ vup cen cen xin xin
ㄒㄧㄣˇ vupr cenj cenf xin8 xinj
ㄒㄧㄣˊ vupe cenf cend xin7 xinf
ㄒㄧㄣˋ vupd cenk cenj xin9 xinl
ㄒㄧㄤ vull cet cek xik xig
ㄒㄧㄤˇ vullr cetj cekf xik8 xigj
ㄒㄧㄤˊ vulle cetf cekd xik7 xigf
ㄒㄧㄤˋ vulld cetk cekj xik9 xigl
ㄒㄧㄥ vun cel cel xig xim
ㄒㄧㄥˇ vunr celj celf xig8 ximj
ㄒㄧㄥˊ vune celf celd xig7 ximf
ㄒㄧㄥˋ vund celk celj xig9 ximl
ㄒㄧˇ vur cej cef xi8 xij
ㄒㄧˊ vue cef ced xi7 xif
ㄒㄧˋ vud cek cej xi9 xil
ㄒㄩ vm cu cu xv xy
ㄒㄩㄝ vmb cuw cue xve xyc
ㄒㄩㄝˇ vmbr cuwj cuef xve8 xycj
ㄒㄩㄝˊ vmbe cuwf cued xve7 xycf
ㄒㄩㄝˋ vmbd cuwk cuej xve9 xycl
ㄒㄩㄢ vmoo cum cum xvm xyb
ㄒㄩㄢˇ vmoor cumj cumf xvm8 xybj
ㄒㄩㄢˊ vmooe cumf cumd xvm7 xybf
ㄒㄩㄢˋ vmood cumk cumj xvm9 xybl
ㄒㄩㄣ vmp cun cun xvn xyn
ㄒㄩㄣˊ vmpe cunf cund xvn7 xynf
ㄒㄩㄣˋ vmpd cunk cunj xvn9 xynl
ㄒㄩㄥ vmn cul cul xvg xym
ㄒㄩㄥˇ vmnr culj culf xvg8 xymj
ㄒㄩㄥˊ vmne culf culd xvg7 xymf
ㄒㄩㄥˋ vmnd culk culj xvg9 xyml
ㄒㄩˇ vmr cuj cuf xv8 xyj
ㄒㄩˊ vme cuf cud xv7 xyf
ㄒㄩˋ vmd cuk cuj xv9 xyl
ㄓ tt g j j j
ㄓㄚ ttuu ga jy ja ja
ㄓㄚˇ ttuur gaj jyf ja8 jaj
ㄓㄚˊ ttuue gaf jyd ja7 jaf
ㄓㄚˋ ttuud gak jyj ja9 jal
ㄓㄜ ttk gr jg je je
ㄓㄜˇ ttkr grj jgf je8 jej
ㄓㄜˊ ttke grf jgd je7 jef
ㄓㄜˋ ttkd grk jgj je9 jel
ㄓㄜ˙ ttky grd jgs je0 jed
ㄓㄞ ttii gi ji jy jh
ㄓㄞˇ ttiir gij jif jy8 jhj
ㄓㄞˊ ttiie gif jid jy7 jhf
ㄓㄞˋ ttiid gik jij jy9 jhl
ㄓㄟˋ ttod gqk jaj jt9 jkl
ㄓㄠ ttl gz jw jf jw
ㄓㄠˇ ttlr gzj jwf jf8 jwj
ㄓㄠˊ ttle gzf jwd jf7 jwf
ㄓㄠˋ ttld gzk jwj jf9 jwl
ㄓㄡ ttm gp jo jw jv
ㄓㄡˇ ttmr gpj jof jw8 jvj
ㄓㄡˊ ttme gpf jod jw7 jvf
ㄓㄡˋ ttmd gpk joj jw9 jvl
ㄓㄢ ttoo gm jm jm jb
ㄓㄢˇ ttoor gmj jmf jm8 jbj
ㄓㄢˋ ttood gmk jmj jm9 jbl
ㄓㄣ ttp gn jn jn jn
ㄓㄣˇ ttpr gnj jnf jn8 jnj
ㄓㄣˊ ttpe gnf jnd jn7 jnf
ㄓㄣˋ ttpd gnk jnj jn9 jnl
ㄓㄤ ttll gt jk jk jg
ㄓㄤˇ ttllr gtj jkf jk8 jgj
ㄓㄤˋ ttlld gtk jkj jk9 jgl
ㄓㄥ ttn gl jl jg jm
ㄓㄥˇ ttnr glj jlf jg8 jmj
ㄓㄥˋ ttnd glk jlj jg9 jml
ㄓㄨ ttj gx jx ju ju
ㄓㄨㄚ ttju gxa jxy jua jua
ㄓㄨㄚˇ ttjur gxaj jxyf jua8 juaj
ㄓㄨㄛ ttji gxo jxh juo juo
ㄓㄨㄛˊ ttjie gxof jxhd juo7 juof
ㄓㄨㄛˋ ttjid gxok jxhj juo9 juol
ㄓㄨㄞ ttjii gxi jxi juy juh
ㄓㄨㄞˇ ttjiir gxij jxif juy8 juhj
ㄓㄨㄞˋ ttjiid gxik jxij juy9 juhl
ㄓㄨㄟ ttjo gxq jxa jut juk
ㄓㄨㄟˇ ttjor gxqj jxaf jut8 jukj
ㄓㄨㄟˋ ttjod gxqk jxaj jut9 jukl
ㄓㄨㄢ ttjoo gxm jxm jum jub
ㄓㄨㄢˇ ttjoor gxmj jxmf jum8 jubj
ㄓㄨㄢˋ ttjood gxmk jxmj jum9 jubl
ㄓㄨㄣ ttjp gxn jxn jun jun
ㄓㄨㄣˇ ttjpr gxnj jxnf jun8 junj
ㄓㄨㄣˋ ttjpd gxnk jxnj jun9 junl
ㄓㄨㄤ ttjll gxt jxk juk jug
ㄓㄨㄤˇ ttjllr gxtj jxkf juk8 jugj
ㄓㄨㄤˋ ttjlld gxtk jxkj juk9 jugl
ㄓㄨㄥ ttjn gxl jxl jug jum
ㄓㄨㄥˇ ttjnr gxlj jxlf jug8 jumj
ㄓㄨㄥˋ ttjnd gxlk jxlj jug9 juml
ㄓㄨˇ ttjr gxj jxf ju8 juj
ㄓㄨˊ ttje gxf jxd ju7 juf
ㄓㄨˋ ttjd gxk jxj ju9 jul
ㄓˇ ttr gj jf j8 jj
ㄓˊ tte gf jd j7 jf
ㄓˋ ttd gk jj j9 jl
ㄔ `NULL y `NULL q `NULL
ㄔ_ t_ `NULL v_ `NULL q_
ㄔㄚ tuu ya vy qa qa
ㄔㄚˇ tuur yaj vyf qa8 qaj
ㄔㄚˊ tuue yaf vyd qa7 qaf
ㄔㄚˋ tuud yak vyj qa9 qal
ㄔㄜ `NULL yr `NULL qe qe
ㄔㄜ_ tk_ `NULL vg_ `NULL `NULL
ㄔㄜˇ tkr yrj vgf qe8 qej
ㄔㄜˋ tkd yrk vgj qe9 qel
ㄔㄞ tii yi vi qy qh
ㄔㄞˇ tiir yij vif qy8 qhj
ㄔㄞˊ tiie yif vid qy7 qhf
ㄔㄞˋ tiid yik vij qy9 qhl
ㄔㄠ tl yz vw qf qw
ㄔㄠˇ tlr yzj vwf qf8 qwj
ㄔㄠˊ tle yzf vwd qf7 qwf
ㄔㄠˋ tld yzk vwj qf9 qwl
ㄔㄡ tm yp vo qw qv
ㄔㄡˇ tmr ypj vof qw8 qvj
ㄔㄡˊ tme ypf vod qw7 qvf
ㄔㄡˋ tmd ypk voj qw9 qvl
ㄔㄢ `NULL ym `NULL qm qb
ㄔㄢ_ too_ `NULL vm_ `NULL `NULL
ㄔㄢˇ toor ymj vmf qm8 qbj
ㄔㄢˊ tooe ymf vmd qm7 qbf
ㄔㄢˋ tood ymk vmj qm9 qbl
ㄔㄣ `NULL yn `NULL qn qn
ㄔㄣ_ tp_ `NULL vn_ `NULL `NULL
ㄔㄣˇ tpr ynj vnf qn8 qnj
ㄔㄣˊ tpe ynf vnd qn7 qnf
ㄔㄣˋ tpd ynk vnj qn9 qnl
ㄔㄣ˙ tpy ynd vns qn0 qnd
ㄔㄤ `NULL yt `NULL qk qg
ㄔㄤ_ tll_ `NULL vk_ `NULL `NULL
ㄔㄤˇ tllr ytj vkf qk8 qgj
ㄔㄤˊ tlle ytf vkd qk7 qgf
ㄔㄤˋ tlld ytk vkj qk9 qgl
ㄔㄥ `NULL yl `NULL qg qm
ㄔㄥ_ tn_ `NULL vl_ `NULL `NULL
ㄔㄥˇ tnr ylj vlf qg8 qmj
ㄔㄥˊ tne ylf vld qg7 qmf
ㄔㄥˋ tnd ylk vlj qg9 qml
ㄔㄨ tj yx vx qu qu
ㄔㄨㄚ tju yxa vxy qua qua
ㄔㄨㄚˇ tjur yxaj vxyf qua8 quaj
ㄔㄨㄚˋ tjud yxak vxyj qua9 qual
ㄔㄨㄛ tji yxo vxh quo quo
ㄔㄨㄛˋ tjid yxok vxhj quo9 quol
ㄔㄨㄞ tjii yxi vxi quy quh
ㄔㄨㄞˇ tjiir yxij vxif quy8 quhj
ㄔㄨㄞˊ tjiie yxif vxid quy7 quhf
ㄔㄨㄞˋ tjiid yxik vxij quy9 quhl
ㄔㄨㄟ tjo yxq vxa qut quk
ㄔㄨㄟˇ tjor yxqj vxaf qut8 qukj
ㄔㄨㄟˊ tjoe yxqf vxad qut7 qukf
ㄔㄨㄟˋ tjod yxqk vxaj qut9 qukl
ㄔㄨㄢ tjoo yxm vxm qum qub
ㄔㄨㄢˇ tjoor yxmj vxmf qum8 qubj
ㄔㄨㄢˊ tjooe yxmf vxmd qum7 qubf
ㄔㄨㄢˋ tjood yxmk vxmj qum9 qubl
ㄔㄨㄣ tjp yxn vxn qun qun
ㄔㄨㄣˇ tjpr yxnj vxnf qun8 qunj
ㄔㄨㄣˊ tjpe yxnf vxnd qun7 qunf
ㄔㄨㄤ tjll yxt vxk quk qug
ㄔㄨㄤˇ tjllr yxtj vxkf quk8 qugj
ㄔㄨㄤˊ tjlle yxtf vxkd quk7 qugf
ㄔㄨㄤˋ tjlld yxtk vxkj quk9 qugl
ㄔㄨㄥ tjn yxl vxl qug qum
ㄔㄨㄥˇ tjnr yxlj vxlf qug8 qumj
ㄔㄨㄥˊ tjne yxlf vxld qug7 qumf
ㄔㄨㄥˋ tjnd yxlk vxlj qug9 quml
ㄔㄨˇ tjr yxj vxf qu8 quj
ㄔㄨˊ tje yxf vxd qu7 quf
ㄔㄨˋ tjd yxk vxj qu9 qul
ㄔˇ tr yj vf q8 qj
ㄔˊ te yf vd q7 qf
ㄔˋ td yk vj q9 ql
ㄕ g c c x `NULL
ㄕ_ `NULL `NULL `NULL `NULL x_
ㄕㄚ guu ca cy xa xa
ㄕㄚˇ guur caj cyf xa8 xaj
ㄕㄚˊ guue caf cyd xa7 xaf
ㄕㄚˋ guud cak cyj xa9 xal
ㄕㄚ˙ guuy cad cys xa0 xad
ㄕㄜ gk cr cg xe xe
ㄕㄜˇ gkr crj cgf xe8 xej
ㄕㄜˊ gke crf cgd xe7 xef
ㄕㄜˋ gkd crk cgj xe9 xel
ㄕㄞ gii ci ci xy xh
ㄕㄞˇ giir cij cif xy8 xhj
ㄕㄞˋ giid cik cij xy9 xhl
ㄕㄟˊ goe cqf cad xt7 xkf
ㄕㄠ gl cz cw xf xw
ㄕㄠˇ glr czj cwf xf8 xwj
ㄕㄠˊ gle czf cwd xf7 xwf
ㄕㄠˋ gld czk cwj xf9 xwl
ㄕㄡ gm cp co xw xv
ㄕㄡˇ gmr cpj cof xw8 xvj
ㄕㄡˊ gme cpf cod xw7 xvf
ㄕㄡˋ gmd cpk coj xw9 xvl
ㄕㄢ goo cm cm xm xb
ㄕㄢˇ goor cmj cmf xm8 xbj
ㄕㄢˊ gooe cmf cmd xm7 xbf
ㄕㄢˋ good cmk cmj xm9 xbl
ㄕㄣ gp cn cn xn xn
ㄕㄣˇ gpr cnj cnf xn8 xnj
ㄕㄣˊ gpe cnf cnd xn7 xnf
ㄕㄣˋ gpd cnk cnj xn9 xnl
ㄕㄤ gll ct ck xk xg
ㄕㄤˇ gllr ctj ckf xk8 xgj
ㄕㄤˋ glld ctk ckj xk9 xgl
ㄕㄤ˙ glly ctd cks xk0 xgd
ㄕㄥ gn cl cl xg xm
ㄕㄥˇ gnr clj clf xg8 xmj
ㄕㄥˊ gne clf cld xg7 xmf
ㄕㄥˋ gnd clk clj xg9 xml
ㄕㄨ gj cx cx xu xu
ㄕㄨㄚ gju cxa cxy xua xua
ㄕㄨㄚˇ gjur cxaj cxyf xua8 xuaj
ㄕㄨㄚˋ gjud cxak cxyj xua9 xual
ㄕㄨㄛ gji cxo cxh xuo xuo
ㄕㄨㄛˋ gjid cxok cxhj xuo9 xuol
ㄕㄨㄞ gjii cxi cxi xuy xuh
ㄕㄨㄞˇ gjiir cxij cxif xuy8 xuhj
ㄕㄨㄞˋ gjiid cxik cxij xuy9 xuhl
ㄕㄨㄟ gjo cxq cxa xut xuk
ㄕㄨㄟˇ gjor cxqj cxaf xut8 xukj
ㄕㄨㄟˊ gjoe cxqf cxad xut7 xukf
ㄕㄨㄟˋ gjod cxqk cxaj xut9 xukl
ㄕㄨㄢ gjoo cxm cxm xum xub
ㄕㄨㄢˋ gjood cxmk cxmj xum9 xubl
ㄕㄨㄣˇ gjpr cxnj cxnf xun8 xunj
ㄕㄨㄣˋ gjpd cxnk cxnj xun9 xunl
ㄕㄨㄤ gjll cxt cxk xuk xug
ㄕㄨㄤˇ gjllr cxtj cxkf xuk8 xugj
ㄕㄨㄤˊ gjlle cxtf cxkd xuk7 xugf
ㄕㄨㄤˋ gjlld cxtk cxkj xuk9 xugl
ㄕㄨˇ gjr cxj cxf xu8 xuj
ㄕㄨˊ gje cxf cxd xu7 xuf
ㄕㄨˋ gjd cxk cxj xu9 xul
ㄕˇ gr cj cf x8 xj
ㄕˊ ge cf cd x7 xf
ㄕˋ gd ck cj x9 xl
ㄕ˙ gy cd cs x0 xd
ㄖㄜˇ bkr jrj rgf re8 rej
ㄖㄜˋ bkd jrk rgj re9 rel
ㄖㄠˇ blr jzj rwf rf8 rwj
ㄖㄠˊ ble jzf rwd rf7 rwf
ㄖㄠˋ bld jzk rwj rf9 rwl
ㄖㄡˇ bmr jpj rof rw8 rvj
ㄖㄡˊ bme jpf rod rw7 rvf
ㄖㄡˋ bmd jpk roj rw9 rvl
ㄖㄢˇ boor jmj rmf rm8 rbj
ㄖㄢˊ booe jmf rmd rm7 rbf
ㄖㄢˋ bood jmk rmj rm9 rbl
ㄖㄣˇ bpr jnj rnf rn8 rnj
ㄖㄣˊ bpe jnf rnd rn7 rnf
ㄖㄣˋ bpd jnk rnj rn9 rnl
ㄖㄤ bll jt rk rk rg
ㄖㄤˇ bllr jtj rkf rk8 rgj
ㄖㄤˊ blle jtf rkd rk7 rgf
ㄖㄤˋ blld jtk rkj rk9 rgl
ㄖㄥ bn jl rl rg rm
ㄖㄥˇ bnr jlj rlf rg8 rmj
ㄖㄥˊ bne jlf rld rg7 rmf
ㄖㄥˋ bnd jlk rlj rg9 rml
ㄖㄨㄛˊ bjie jxof rxhd ruo7 ruof
ㄖㄨㄛˋ bjid jxok rxhj ruo9 ruol
ㄖㄨㄟˇ bjor jxqj rxaf rut8 rukj
ㄖㄨㄟˊ bjoe jxqf rxad rut7 rukf
ㄖㄨㄟˋ bjod jxqk rxaj rut9 rukl
ㄖㄨㄢˇ bjoor jxmj rxmf rum8 rubj
ㄖㄨㄢˊ bjooe jxmf rxmd rum7 rubf
ㄖㄨㄢˋ bjood jxmk rxmj rum9 rubl
ㄖㄨㄣˇ bjpr jxnj rxnf run8 runj
ㄖㄨㄣˊ bjpe jxnf rxnd run7 runf
ㄖㄨㄣˋ bjpd jxnk rxnj run9 runl
ㄖㄨㄥˇ bjnr jxlj rxlf rug8 rumj
ㄖㄨㄥˊ bjne jxlf rxld rug7 rumf
ㄖㄨㄥˋ bjnd jxlk rxlj rug9 ruml
ㄖㄨˇ bjr jxj rxf ru8 ruj
ㄖㄨˊ bje jxf rxd ru7 ruf
ㄖㄨˋ bjd jxk rxj ru9 rul
ㄖˋ bd jk rj r9 rl
ㄗ y q z z z
ㄗㄚ yuu qa zy za za
ㄗㄚˇ yuur qaj zyf za8 zaj
ㄗㄚˊ yuue qaf zyd za7 zaf
ㄗㄜˇ ykr qrj zgf ze8 zej
ㄗㄜˊ yke qrf zgd ze7 zef
ㄗㄜˋ ykd qrk zgj ze9 zel
ㄗㄞ yii qi zi zy zh
ㄗㄞˇ yiir qij zif zy8 zhj
ㄗㄞˋ yiid qik zij zy9 zhl
ㄗㄟˊ yoe qqf zad zt7 zkf
ㄗㄠ yl qz zw zf zw
ㄗㄠˇ ylr qzj zwf zf8 zwj
ㄗㄠˊ yle qzf zwd zf7 zwf
ㄗㄠˋ yld qzk zwj zf9 zwl
ㄗㄡ ym qp zo zw zv
ㄗㄡˇ ymr qpj zof zw8 zvj
ㄗㄡˋ ymd qpk zoj zw9 zvl
ㄗㄢ yoo qm zm zm zb
ㄗㄢˇ yoor qmj zmf zm8 zbj
ㄗㄢˊ yooe qmf zmd zm7 zbf
ㄗㄢˋ yood qmk zmj zm9 zbl
ㄗㄣ yp qn zn zn zn
ㄗㄣˇ ypr qnj znf zn8 znj
ㄗㄣˋ ypd qnk znj zn9 znl
ㄗㄤ yll qt zk zk zg
ㄗㄤˇ yllr qtj zkf zk8 zgj
ㄗㄤˋ ylld qtk zkj zk9 zgl
ㄗㄥ yn ql zl zg zm
ㄗㄥˇ ynr qlj zlf zg8 zmj
ㄗㄥˋ ynd qlk zlj zg9 zml
ㄗㄨ yj qx zx zu zu
ㄗㄨㄛ yji qxo zxh zuo zuo
ㄗㄨㄛˇ yjir qxoj zxhf zuo8 zuoj
ㄗㄨㄛˊ yjie qxof zxhd zuo7 zuof
ㄗㄨㄛˋ yjid qxok zxhj zuo9 zuol
ㄗㄨㄛ˙ yjiy qxod zxhs zuo0 zuod
ㄗㄨㄟ yjo qxq zxa zut zuk
ㄗㄨㄟˇ yjor qxqj zxaf zut8 zukj
ㄗㄨㄟˋ yjod qxqk zxaj zut9 zukl
ㄗㄨㄢ yjoo qxm zxm zum zub
ㄗㄨㄢˇ yjoor qxmj zxmf zum8 zubj
ㄗㄨㄢˋ yjood qxmk zxmj zum9 zubl
ㄗㄨㄣ yjp qxn zxn zun zun
ㄗㄨㄣˇ yjpr qxnj zxnf zun8 zunj
ㄗㄨㄣˋ yjpd qxnk zxnj zun9 zunl
ㄗㄨㄥ yjn qxl zxl zug zum
ㄗㄨㄥˇ yjnr qxlj zxlf zug8 zumj
ㄗㄨㄥˋ yjnd qxlk zxlj zug9 zuml
ㄗㄨˇ yjr qxj zxf zu8 zuj
ㄗㄨˊ yje qxf zxd zu7 zuf
ㄗㄨˋ yjd qxk zxj zu9 zul
ㄗˇ yr qj zf z8 zj
ㄗˊ ye qf zd z7 zf
ㄗˋ yd qk zj z9 zl
ㄗ˙ yy qd zs z0 zd
ㄘ h w a c c
ㄘㄚ huu wa ay ca ca
ㄘㄚˇ huur waj ayf ca8 caj
ㄘㄚˋ huud wak ayj ca9 cal
ㄘㄜˋ hkd wrk agj ce9 cel
ㄘㄞ hii wi ai cy ch
ㄘㄞˇ hiir wij aif cy8 chj
ㄘㄞˊ hiie wif aid cy7 chf
ㄘㄞˋ hiid wik aij cy9 chl
ㄘㄠ hl wz aw cf cw
ㄘㄠˇ hlr wzj awf cf8 cwj
ㄘㄠˊ hle wzf awd cf7 cwf
ㄘㄠˋ hld wzk awj cf9 cwl
ㄘㄡ hm wp ao cw cv
ㄘㄡˇ hmr wpj aof cw8 cvj
ㄘㄡˊ hme wpf aod cw7 cvf
ㄘㄡˋ hmd wpk aoj cw9 cvl
ㄘㄢ hoo wm am cm cb
ㄘㄢˇ hoor wmj amf cm8 cbj
ㄘㄢˊ hooe wmf amd cm7 cbf
ㄘㄢˋ hood wmk amj cm9 cbl
ㄘㄣ hp wn an cn cn
ㄘㄣˊ hpe wnf and cn7 cnf
ㄘㄤ hll wt ak ck cg
ㄘㄤˇ hllr wtj akf ck8 cgj
ㄘㄤˊ hlle wtf akd ck7 cgf
ㄘㄤˋ hlld wtk akj ck9 cgl
ㄘㄥ hn wl al cg cm
ㄘㄥˇ hnr wlj alf cg8 cmj
ㄘㄥˊ hne wlf ald cg7 cmf
ㄘㄥˋ hnd wlk alj cg9 cml
ㄘㄨ hj wx ax cu cu
ㄘㄨㄛ hji wxo axh cuo cuo
ㄘㄨㄛˇ hjir wxoj axhf cuo8 cuoj
ㄘㄨㄛˊ hjie wxof axhd cuo7 cuof
ㄘㄨㄛˋ hjid wxok axhj cuo9 cuol
ㄘㄨㄟ hjo wxq axa cut cuk
ㄘㄨㄟˇ hjor wxqj axaf cut8 cukj
ㄘㄨㄟˋ hjod wxqk axaj cut9 cukl
ㄘㄨㄢ hjoo wxm axm cum cub
ㄘㄨㄢˇ hjoor wxmj axmf cum8 cubj
ㄘㄨㄢˊ hjooe wxmf axmd cum7 cubf
ㄘㄨㄢˋ hjood wxmk axmj cum9 cubl
ㄘㄨㄣ hjp wxn axn cun cun
ㄘㄨㄣˇ hjpr wxnj axnf cun8 cunj
ㄘㄨㄣˊ hjpe wxnf axnd cun7 cunf
ㄘㄨㄣˋ hjpd wxnk axnj cun9 cunl
ㄘㄨㄥ hjn wxl axl cug cum
ㄘㄨㄥˇ hjnr wxlj axlf cug8 cumj
ㄘㄨㄥˊ hjne wxlf axld cug7 cumf
ㄘㄨㄥˋ hjnd wxlk axlj cug9 cuml
ㄘㄨˇ hjr wxj axf cu8 cuj
ㄘㄨˊ hje wxf axd cu7 cuf
ㄘㄨˋ hjd wxk axj cu9 cul
ㄘˇ hr wj af c8 cj
ㄘˊ he wf ad c7 cf
ㄘˋ hd wk aj c9 cl
ㄙ n s s s s
ㄙㄚ nuu sa sy sa sa
ㄙㄚˇ nuur saj syf sa8 saj
ㄙㄚˋ nuud sak syj sa9 sal
ㄙㄚ˙ nuuy sad sys sa0 sad
ㄙㄜ nk sr sg se se
ㄙㄜˋ nkd srk sgj se9 sel
ㄙㄞ nii si si sy sh
ㄙㄞˇ niir sij sif sy8 shj
ㄙㄞˊ niie sif sid sy7 shf
ㄙㄞˋ niid sik sij sy9 shl
ㄙㄟ no sq sa st sk
ㄙㄠ nl sz sw sf sw
ㄙㄠˇ nlr szj swf sf8 swj
ㄙㄠˋ nld szk swj sf9 swl
ㄙㄡ nm sp so sw sv
ㄙㄡˇ nmr spj sof sw8 svj
ㄙㄡˋ nmd spk soj sw9 svl
ㄙㄢ noo sm sm sm sb
ㄙㄢˇ noor smj smf sm8 sbj
ㄙㄢˋ nood smk smj sm9 sbl
ㄙㄣ np sn sn sn sn
ㄙㄣˇ npr snj snf sn8 snj
ㄙㄤ nll st sk sk sg
ㄙㄤˇ nllr stj skf sk8 sgj
ㄙㄤˋ nlld stk skj sk9 sgl
ㄙㄥ nnn sl sl sg sm
ㄙㄥˋ nnnd slk slj sg9 sml
ㄙㄨ nj sx sx su su
ㄙㄨㄛ nji sxo sxh suo suo
ㄙㄨㄛˇ njir sxoj sxhf suo8 suoj
ㄙㄨㄛˊ njie sxof sxhd suo7 suof
ㄙㄨㄛˋ njid sxok sxhj suo9 suol
ㄙㄨㄟ njo sxq sxa sut suk
ㄙㄨㄟˇ njor sxqj sxaf sut8 sukj
ㄙㄨㄟˊ njoe sxqf sxad sut7 sukf
ㄙㄨㄟˋ njod sxqk sxaj sut9 sukl
ㄙㄨㄢ njoo sxm sxm sum sub
ㄙㄨㄢˇ njoor sxmj sxmf sum8 subj
ㄙㄨㄢˋ njood sxmk sxmj sum9 subl
ㄙㄨㄣ njp sxn sxn sun sun
ㄙㄨㄣˇ njpr sxnj sxnf sun8 sunj
ㄙㄨㄣˋ njpd sxnk sxnj sun9 sunl
ㄙㄨㄥ njn sxl sxl sug sum
ㄙㄨㄥˇ njnr sxlj sxlf sug8 sumj
ㄙㄨㄥˊ njne sxlf sxld sug7 sumf
ㄙㄨㄥˋ njnd sxlk sxlj sug9 suml
ㄙㄨˇ njr sxj sxf su8 suj
ㄙㄨˊ nje sxf sxd su7 suf
ㄙㄨˋ njd sxk sxj su9 sul
ㄙˇ nr sj sf s8 sj
ㄙˋ nd sk sj s9 sl
ㄚ uu a y a a
ㄚˊ uue af yd a7 af
ㄚˋ uud ak yj a9 al
ㄚ˙ uuy ad ys a0 ad
ㄛ `NULL o `NULL o o
ㄛ_ i_ `NULL h_ `NULL `NULL
ㄛˇ ir oj hf o8 oj
ㄛˊ ie of hd o7 of
ㄛˋ id ok hj o9 ol
ㄜ `NULL r `NULL e e
ㄜ_ k_ `NULL g_ `NULL `NULL
ㄜˇ kr rj gf e8 ej
ㄜˊ ke rf gd e7 ef
ㄜˋ kd rk gj e9 el
ㄝˇ `br `wj `ef `e8 `cj
ㄝˊ `be `wf `ed `e7 `cf
ㄝˋ `bd `wk `ej `e9 `cl
ㄝ˙ `by `wd `es `e0 `cd
ㄞ ii i i y `h
ㄞ_ `NULL `NULL `NULL `NULL h_
ㄞˇ iir ij if y8 hj
ㄞˊ iie if id y7 hf
ㄞˋ iid ik ij y9 hl
ㄟˋ od `qk `aj t9 kl
ㄠ l z w `NULL w
ㄠ_ `NULL `NULL `NULL f_ `NULL
ㄠˇ lr zj wf f8 wj
ㄠˊ le zf wd f7 wf
ㄠˋ ld zk wj f9 wl
ㄡ m `NULL o w v
ㄡ_ `NULL p_ `NULL `NULL `NULL
ㄡˇ mr pj of w8 vj
ㄡˊ me pf od w7 vf
ㄡˋ md pk oj w9 vl
ㄡ˙ my pd os w0 vd
ㄢ_ oo_ m_ m_ m_ b_
ㄢˇ oor mj mf m8 bj
ㄢˊ ooe mf md m7 bf
ㄢˋ ood mk mj m9 bl
ㄣ_ p_ n_ n_ n_ n_
ㄣˇ pr nj nf n8 nj
ㄣˊ pe nf nd n7 nf
ㄣˋ pd nk nj n9 nl
ㄣ˙ py nd ns n0 nd
ㄤ_ ll_ t_ k_ k_ g_
ㄤˇ llr tj kf k8 gj
ㄤˊ lle tf kd k7 gf
ㄤˋ lld tk kj k9 gl
ㄥ_ nn_ l_ `l_ g_ m_
ㄥˋ nnd lk `lj g9 ml
ㄦ_ pp_ h_ l_ l_ t_
ㄦˇ ppr hj lf l8 tj
ㄦˊ ppe hf ld l7 tf
ㄦˋ ppd hk lj l9 tl
ㄦ˙ ppy hd ls l0 td
ㄧ u e e i i
ㄧㄚ uuu ea ey ia ia
ㄧㄚˇ uuur eaj eyf ia8 iaj
ㄧㄚˊ uuue eaf eyd ia7 iaf
ㄧㄚˋ uuud eak eyj ia9 ial
ㄧㄚ˙ uuuy ead eys ia0 iad
ㄧㄛ ui eo eh io io
ㄧㄛ˙ uiy eod ehs io0 iod
ㄧㄝ ub ew ee ie ic
ㄧㄝˇ ubr ewj eef ie8 icj
ㄧㄝˊ ube ewf eed ie7 icf
ㄧㄝˋ ubd ewk eej ie9 icl
ㄧㄝ˙ uby ewd ees ie0 icd
ㄧㄞˊ uiie eif eid iy7 ihf
ㄧㄠ ul ez ew if iw
ㄧㄠˇ ulr ezj ewf if8 iwj
ㄧㄠˊ ule ezf ewd if7 iwf
ㄧㄠˋ uld ezk ewj if9 iwl
ㄧㄡ um ep eo iw iv
ㄧㄡˇ umr epj eof iw8 ivj
ㄧㄡˊ ume epf eod iw7 ivf
ㄧㄡˋ umd epk eoj iw9 ivl
ㄧㄢ uoo em em im ib
ㄧㄢˇ uoor emj emf im8 ibj
ㄧㄢˊ uooe emf emd im7 ibf
ㄧㄢˋ uood emk emj im9 ibl
ㄧㄣ up en en in in
ㄧㄣˇ upr enj enf in8 inj
ㄧㄣˊ upe enf end in7 inf
ㄧㄣˋ upd enk enj in9 inl
ㄧㄤ ull et ek ik ig
ㄧㄤˇ ullr etj ekf ik8 igj
ㄧㄤˊ ulle etf ekd ik7 igf
ㄧㄤˋ ulld etk ekj ik9 igl
ㄧㄥ un el el ig im
ㄧㄥˇ unr elj elf ig8 imj
ㄧㄥˊ une elf eld ig7 imf
ㄧㄥˋ und elk elj ig9 iml
ㄧˇ ur ej ef i8 ij
ㄧˊ ue ef ed i7 if
ㄧˋ ud ek ej i9 il
ㄨ j x x u u
ㄨㄚ ju xa xy ua ua
ㄨㄚˇ jur xaj xyf ua8 uaj
ㄨㄚˊ jue xaf xyd ua7 uaf
ㄨㄚˋ jud xak xyj ua9 ual
ㄨㄚ˙ juy xad xys ua0 uad
ㄨㄛ ji xo xh uo uo
ㄨㄛˇ jir xoj xhf uo8 uoj
ㄨㄛˋ jid xok xhj uo9 uol
ㄨㄞ jii xi xi uy uh
ㄨㄞˇ jiir xij xif uy8 uhj
ㄨㄞˋ jiid xik xij uy9 uhl
ㄨㄟ jo xq xa ut uk
ㄨㄟˇ jor xqj xaf ut8 ukj
ㄨㄟˊ joe xqf xad ut7 ukf
ㄨㄟˋ jod xqk xaj ut9 ukl
ㄨㄢ joo xm xm um ub
ㄨㄢˇ joor xmj xmf um8 ubj
ㄨㄢˊ jooe xmf xmd um7 ubf
ㄨㄢˋ jood xmk xmj um9 ubl
ㄨㄣ jp xn xn un un
ㄨㄣˇ jpr xnj xnf un8 unj
ㄨㄣˊ jpe xnf xnd un7 unf
ㄨㄣˋ jpd xnk xnj un9 unl
ㄨㄤ jll xt xk uk ug
ㄨㄤˇ jllr xtj xkf uk8 ugj
ㄨㄤˊ jlle xtf xkd uk7 ugf
ㄨㄤˋ jlld xtk xkj uk9 ugl
ㄨㄥ jn xl xl ug um
ㄨㄥˇ jnr xlj xlf ug8 umj
ㄨㄥˋ jnd xlk xlj ug9 uml
ㄨˇ jr xj xf u8 uj
ㄨˊ je xf xd u7 uf
ㄨˋ jd xk xj u9 ul
ㄩ mm u u v y
ㄩㄝ mmb uw ue ve yc
ㄩㄝˇ mmbr uwj uef ve8 ycj
ㄩㄝˋ mmbd uwk uej ve9 ycl
ㄩㄢ mmoo um um vm yb
ㄩㄢˇ mmoor umj umf vm8 ybj
ㄩㄢˊ mmooe umf umd vm7 ybf
ㄩㄢˋ mmood umk umj vm9 ybl
ㄩㄣ mmp un un vn yn
ㄩㄣˇ mmpr unj unf vn8 ynj
ㄩㄣˊ mmpe unf und vn7 ynf
ㄩㄣˋ mmpd unk unj vn9 ynl
ㄩㄥ mmn ul ul vg ym
ㄩㄥˇ mmnr ulj ulf vg8 ymj
ㄩㄥˊ mmne ulf uld vg7 ymf
ㄩㄥˋ mmnd ulk ulj vg9 yml
ㄩˇ mmr uj uf v8 yj
ㄩˊ mme uf ud v7 yf
ㄩˋ mmd uk uj v9 yl
"""
