// (c) 2022 and onwards The vChewing Project (LGPL v3.0 License or later).
// ====================
// This code is released under the SPDX-License-Identifier: `LGPL-3.0-or-later`.

import Foundation
import Homa
import LXAssemblyMaterials4Tests
import Testing

@testable import LexiconAssembly

private let strCakeKey: [String] = ["ㄉㄢˋ", "ㄍㄠ"]
private let strZhongKey: [String] = ["ㄓㄨㄥ"]
private let strBoobsKey: [String] = ["ㄋㄟ", "ㄋㄟ"]
private let expectedReverseLookupResults: [String] = [
  "ㄉㄨㄥ", "ㄏㄢˋ", "ㄏㄜˊ", "ㄏㄜˋ", "ㄏㄜ˙", "ㄏㄨˊ", "ㄏㄨㄛ", "ㄏㄨㄛˊ", "ㄏㄨㄛˋ", "ㄏㄨㄛ˙",
]

// MARK: - LXFacadeTextMapTests

@Suite(.serialized)
struct LXFacadeTextMapTests {
  // MARK: Internal

  @Test
  func testTextMapFixtureLoading() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(!LXATestsData.textMapTestCoreLXData.isEmpty)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: LXATestsData.textMapTestCoreLXData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
    }
    #expect(gramTriples(of: instance.unigramsFor(keyArray: strCakeKey)) == [
      .init(keyArray: strCakeKey, value: "蛋糕", probability: -4.072),
    ])
    #expect(gramTriple(of: instance.getHaninSymbolMenuUnigrams()[1]) == .init(
      keyArray: ["_punctuation_list"],
      value: "，",
      probability: 0.0
    ))
    #expect(gramTriples(of: instance.unigramsFor(keyArray: strBoobsKey)) == [
      .init(keyArray: strBoobsKey, value: "ㄋㄟㄋㄟ", probability: -1.0),
    ])

    instance.setOptions { config in
      config.isCNSEnabled = true
      config.isSymbolEnabled = true
    }
    #expect(gramTriple(of: instance.unigramsFor(keyArray: strCakeKey).last) == .init(
      keyArray: strCakeKey,
      value: "🧁",
      probability: -13.0
    ))
    #expect(instance.unigramsFor(keyArray: strZhongKey).count == 184)
    #expect(gramTriple(of: instance.unigramsFor(keyArray: strBoobsKey).last) == .init(
      keyArray: strBoobsKey,
      value: "☉☉",
      probability: -13.0
    ))
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testLegacyTestLoaderCompatibility() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    #expect(!LXATestsData.textMapTestCoreLXData.isEmpty)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: LXATestsData.textMapTestCoreLXData))
    #expect(instance.unigramsFor(keyArray: strCakeKey).first?.current == "蛋糕")
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testCNSMask() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: LXATestsData.textMapTestCoreLXData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
      config.filterNonCNSReadings = false
      config.alwaysSupplyETenDOSUnigrams = false
    }
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟ"], value: "危", probability: -5.287)
    )
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟˊ"], value: "危", probability: -5.287)
    )

    instance.setOptions { config in
      config.filterNonCNSReadings = true
    }
    // 單一讀音的單漢字不再被濾除，而是 demote score 至 -9.5。
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟ"], value: "危", probability: -9.5)
    )
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟˊ"], value: "危", probability: -5.287)
    )
  }

  @Test
  func testFactoryKeyWithApostropheIsFound() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("k'", [("1 value", -9.9, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["k'"]), "1 value"))
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedOrderIsStable() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1.1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t2
    KEY_COUNT\t2
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t和\t和
    @-9.9\t和\t和
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    ㄏㄜˋ\t0\t1
    ㄏㄨㄛˋ\t1\t1
    """

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ", "ㄏㄨㄛˋ"])
  }

  @Test
  func testFactoryTextMapLoadsWithCRLFLineEndings() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap =
      "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\r\nVERSION\t1.1\r\nTYPE\tTYPING\r\nREADING_SEPARATOR\t-\r\nENTRY_COUNT\t1\r\nKEY_COUNT\t1\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\r\n@-9.9\t和\t和\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\r\nㄏㄜˋ\t0\t1\r\n"

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ"])
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedUsesSingleSegmentGroupedLinesAndCNSEntries() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1.1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t3
    KEY_COUNT\t3
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t宜\t宜
    @-8.8\t便宜\t便宜
    𡜅	-11	7
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    ㄧˊ\t0\t1
    ㄅㄧˋ-ㄧˊ\t1\t1
    ㄌㄩˇ\t2\t1
    """

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "宜") == ["ㄧˊ"])
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "𡜅") == ["ㄌㄩˇ"])
  }

  @Test
  func testFactoryReverseLookupIndexCanBeFlushedAndRebuilt() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1.1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t3
    KEY_COUNT\t3
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t宜\t宜
    @-8.8\t便宜\t便宜
    𡜅\t-11\t7
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    ㄧˊ\t0\t1
    ㄅㄧˋ-ㄧˊ\t1\t1
    ㄌㄩˇ\t2\t1
    """

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "宜") == ["ㄧˊ"])
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "𡜅") == ["ㄌㄩˇ"])
    LXAssembly.LXFacade.flushFactoryReverseLookupIndex()
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "宜") == ["ㄧˊ"])
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "𡜅") == ["ㄌㄩˇ"])
  }

  @Test
  func testFactoryDictionaryDoesNotAutoLoadRevLookupFile() async throws {
    let tempDir = FileManager.default.temporaryDirectory
      .appendingPathComponent(UUID().uuidString)
    try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    defer {
      try? FileManager.default.removeItem(at: tempDir)
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMapPath = tempDir.appendingPathComponent("VanguardFactoryDict4Typing.txtMap")
    let revLookupPath = tempDir.appendingPathComponent("VanguardFactoryDict4RevLookup.revlookup")
    let textMap = makeTextMap([
      ("A", [("和", -9.9, 5)]),
    ])
    let revLookup = "#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\tB\n"

    try textMap.write(to: textMapPath, atomically: true, encoding: .utf8)
    try revLookup.write(to: revLookupPath, atomically: true, encoding: .utf8)

    let originalAsyncLoading = LXAssembly.LXFacade.asyncLoadingUserData
    LXAssembly.LXFacade.asyncLoadingUserData = false
    defer {
      LXAssembly.LXFacade.asyncLoadingUserData = originalAsyncLoading
    }

    let callbackResult: Bool? = await withCheckedContinuation { continuation in
      LXAssembly.LXFacade.connectFactoryDictionary(textMapPath: textMapPath.path) {
        continuation.resume(returning: $0)
      }
    }

    #expect(callbackResult == true)
    #expect(LXAssembly.LXFacade.getFactoryReverseLookupData(with: "B") == nil)
  }

  @Test
  func testFactoryDictionaryRejectsBundledExternalRevLookupFixture() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let bundledFixture = LXATestsData.textMapTestCoreLXData
      + "\n#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\the4\n"

    #expect(!LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: bundledFixture))
    #expect(!LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: bundledFixture))
  }

  @Test
  func testFactoryCNSAndExistenceWithApostropheKey() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    let textMap = makeTextMap([
      ("k'", [("chtval", -9.9, 6), ("cnsval", -11, 7)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(instance.factoryCNSFilterThreadFor(key: "k'") == "cnsval")
    #expect(instance.hasFactoryCoreUnigramsFor(keyArray: ["k'"]))
  }

  @Test
  func testUnderscoreSpecialKeysUseMiscColumn() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    let textMap = makeTextMap([
      ("_alt_punctuation_,", [("，", -9.9, 4)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["_alt_punctuation_,"]), "，"))
    #expect(instance.hasUnigramsFor(keyArray: ["_alt_punctuation_,"]))
  }

  @Test
  func testGeneratedHalfWidthPunctuationRanksBehindCanonicalFullWidth() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    let textMap = makeTextMap([
      ("_punctuation_,", [("，", -9.9, 4)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    let grams = instance.unigramsFor(keyArray: ["_punctuation_,"])
    let fullWidth = grams.first(where: { $0.current == "，" })
    let halfWidth = grams.first(where: { $0.current == "," })

    #expect(gramTriple(of: fullWidth) == .init(keyArray: ["_punctuation_,"], value: "，", probability: -9.9))
    #expect(gramTriple(of: halfWidth) == .init(keyArray: ["_punctuation_,"], value: ",", probability: -9.9001))
  }

  @Test
  func testEqualScoreStandardPunctuationPreservesLexiconOrder() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    let textMap = makeTextMap([
      ("_punctuation_Standard_<", [("，", -9.9, 4), ("〈", -9.9, 4), ("《", -9.9, 4)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    let grams = instance.unigramsFor(keyArray: ["_punctuation_Standard_<"])
    #expect(grams.map(\.current).prefix(3).elementsEqual(["，", "〈", "《"]))
    #expect(grams.prefix(3).allSatisfy { $0.probability == -9.9 })
  }

  @Test
  func testFactoryChoppedQueryDedupsValueByHighestProbability() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: false)
    // 模擬真實辭典中「我」同時以「無調墊底」（ㄨㄛ、低權重）與「聲調專屬」
    // （ㄨㄛˇ、高權重）兩種讀音鍵存在（實際 mcbopomofo 資料即有此結構）；
    // 「喔」僅有無調（ㄨㄛ、中權重）。
    let textMap = makeTextMap([
      ("ㄨㄛ", [("喔", -5.183, 6), ("我", -9.465, 6)]),
      ("ㄨㄛˇ", [("我", -5.043, 6)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    // 狂拼注拼槽「wo」展開的聲調桶查詢（multipleKeys，copilot 窗候選來源）：
    // 修復前 consolidate「先插入者勝」保留無調低權重的「我」（ㄨㄛ、-9.465）、
    // 使其以墊底權重沉到「喔」之後；修復後保留最高機率者（ㄨㄛˇ、-5.043）、
    // 「我」以真實權重浮出且排在「喔」之前。
    let grams = instance.unigramsFor(
      keyArray: [.multipleKeys(["ㄨㄛ", "ㄨㄛˇ"])], partiallyMatch: false
    )
    let woGram = grams.first(where: { $0.current == "我" })
    #expect(gramTriple(of: woGram) == .init(keyArray: ["ㄨㄛˇ"], value: "我", probability: -5.043))
    let indexWo = grams.firstIndex(where: { $0.current == "我" }) ?? -1
    let indexO = grams.firstIndex(where: { $0.current == "喔" }) ?? -1
    #expect(indexWo >= 0 && indexO >= 0 && indexWo < indexO)
  }

  @Test
  func testFactoryStrictSupersetUnigramsFor() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("A-B-C", [("base", -9, 5)]),
      ("A-B-C-Z", [("zval", -1, 5)]),
      ("A-B-C-F", [("fval", -2, 5)]),
      ("A-B-C-M-Q", [("mval", -3, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    let grams = instance.factoryStrictSupersetUnigramsFor(
      subsetKey: "A-B-C",
      subsetKeyArray: ["A", "B", "C"],
      entryType: .chs
    )

    #expect(gramsContainValue(grams, "zval"))
    #expect(gramsContainValue(grams, "fval"))
    #expect(gramsContainValue(grams, "mval"))
    #expect(!gramsContainValue(grams, "base"))
    #expect(grams.first(where: { $0.current == "zval" })?.keyArray.count == 4)
  }

  @Test
  func testFactoryPartialMatchIsControlledByConfigFlag() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("A1-B2", [("partial", -9.9, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.alwaysSupplyETenDOSUnigrams = false
      config.partialMatchEnabled = false
    }
    #expect(instance.unigramsFor(keyArray: ["A&X", "B"]).isEmpty)
    #expect(!instance.hasFactoryCoreUnigramsFor(keyArray: ["A&X", "B"]))

    instance.setOptions { config in
      config.partialMatchEnabled = true
    }
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["A&X", "B"]), "partial"))
    #expect(instance.hasFactoryCoreUnigramsFor(keyArray: ["A&X", "B"]))
  }

  @Test
  func testFactoryPartialMatchDoesNotCrossMatchMiscIntoCore() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("A1-B2", [("miscOnly", -9.9, 4)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.alwaysSupplyETenDOSUnigrams = false
      config.partialMatchEnabled = true
    }

    #expect(instance.unigramsFor(keyArray: ["A", "B"]).isEmpty)
    #expect(!instance.hasFactoryCoreUnigramsFor(keyArray: ["A", "B"]))
  }

  @Test
  func testStrictSupersetStrategyRemainsDistinctFromConfiguredPartialLookup() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("A1-B2", [("exact", -9.9, 5)]),
      ("A1-B2-C3", [("superset", -8.8, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.partialMatchEnabled = true
    }

    let configuredLookup = instance.factoryCoreUnigramsFor(
      key: "A1-B2",
      keyArray: ["A1", "B2"],
      strategy: .configuredLookup
    )
    let strictSupersets = instance.factoryCoreUnigramsFor(
      key: "A1-B2",
      keyArray: ["A1", "B2"],
      strategy: .strictSuperset
    )

    #expect(gramsContainValue(configuredLookup, "exact"))
    #expect(!gramsContainValue(configuredLookup, "superset"))
    #expect(gramsContainValue(strictSupersets, "superset"))
    #expect(!gramsContainValue(strictSupersets, "exact"))
  }

  @Test
  func testAssemblerFacadeMatchesLegacyUnigramSurface() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: LXATestsData.textMapTestCoreLXData))

    instance.setOptions { config in
      config.isCNSEnabled = true
      config.isSymbolEnabled = true
    }

    let legacySurface = gramTriples(of: instance.unigramsFor(keyArray: strCakeKey))
    let cakePossibleKeys = strCakeKey.map { Homa.PossibleKey.singleKey($0) }
    let assemblerSurface = instance.lxQuerier.grams(for: cakePossibleKeys).map {
      GramSnapshot(keyArray: $0.keyArray, value: $0.current, probability: $0.probability)
    }

    #expect(assemblerSurface == legacySurface)
    #expect(instance.lxQuerier.grams(for: cakePossibleKeys).allSatisfy { $0.previous == nil })
    #expect(instance.lxQuerier.hasGrams(for: strCakeKey) == instance.hasUnigramsFor(keyArray: strCakeKey))
  }

  @Test
  func testNonKanjiHiraganaAndFWZeroAreQueryableViaNormalReading() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -13.0, typeID: 8),
        (value: "ぁ", probability: -13.0, typeID: 8),
      ]),
      ("ㄌㄧㄥˊ", [
        (value: "零", probability: -5.0, typeID: 5),
        (value: "〇", probability: -5.261, typeID: 8),
      ]),
    ])

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(gramsContainValue(grams4A, "あ"))
    #expect(gramsContainValue(grams4A, "ぁ"))

    let grams4Ling = instance.unigramsFor(keyArray: ["ㄌㄧㄥˊ"])
    #expect(gramsContainValue(grams4Ling, "零"))
    #expect(gramsContainValue(grams4Ling, "〇"))

    #expect(instance.hasUnigramsForFast(keyArray: ["ㄚ"]))
    #expect(instance.hasUnigramsForFast(keyArray: ["ㄌㄧㄥˊ"]))
  }

  @Test
  func testSuppressFactoryKanaSyllablesCanBeToggled() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -13.0, typeID: 8),
      ]),
      ("kana_only_i", [
        (value: "い", probability: -13.0, typeID: 8),
      ]),
      ("ㄎㄧㄚ", [
        (value: "家", probability: -5.0, typeID: 5),
        (value: "きゃ", probability: -13.0, typeID: 8),
      ]),
      ("ㄌㄧㄥˊ", [
        (value: "零", probability: -5.0, typeID: 5),
        (value: "〇", probability: -5.261, typeID: 8),
      ]),
    ])

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.suppressFactoryUnigramsOfKanaSyllables = false
    }
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["ㄚ"]), "あ"))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["kana_only_i"]), "い"))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["ㄎㄧㄚ"]), "きゃ"))
    #expect(instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))

    instance.setOptions { config in
      config.suppressFactoryUnigramsOfKanaSyllables = true
    }

    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(!gramsContainValue(grams4A, "あ"))

    let grams4I = instance.unigramsFor(keyArray: ["kana_only_i"])
    #expect(grams4I.isEmpty)

    let grams4Kia = instance.unigramsFor(keyArray: ["ㄎㄧㄚ"])
    #expect(gramsContainValue(grams4Kia, "家"))
    #expect(!gramsContainValue(grams4Kia, "きゃ"))

    let grams4Ling = instance.unigramsFor(keyArray: ["ㄌㄧㄥˊ"])
    #expect(gramsContainValue(grams4Ling, "零"))
    #expect(gramsContainValue(grams4Ling, "〇"))

    #expect(!instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))
  }

  @Test
  func testSuppressFactoryKanaSyllablesStillWorksWithPartialMatchEnabled() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("kana_only_i", [
        (value: "い", probability: -13.0, typeID: 8),
      ]),
      ("ㄎㄧㄚ", [
        (value: "家", probability: -5.0, typeID: 5),
        (value: "きゃ", probability: -13.0, typeID: 8),
      ]),
    ])

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.partialMatchEnabled = true
      config.suppressFactoryUnigramsOfKanaSyllables = false
    }
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["kana_only_i"]), "い"))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["ㄎㄧㄚ"]), "きゃ"))
    #expect(instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))

    instance.setOptions { config in
      config.partialMatchEnabled = true
      config.suppressFactoryUnigramsOfKanaSyllables = true
    }

    #expect(instance.unigramsFor(keyArray: ["kana_only_i"]).isEmpty)

    let grams4Kia = instance.unigramsFor(keyArray: ["ㄎㄧㄚ"])
    #expect(gramsContainValue(grams4Kia, "家"))
    #expect(!gramsContainValue(grams4Kia, "きゃ"))

    #expect(!instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))
  }

  @Test
  func testLetterPunctuationRemainsUnderscoreKeyed() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -13.0, typeID: 8),
      ]),
      ("_punctuation_comma", [
        (value: "，", probability: 0.0, typeID: 4),
      ]),
    ])

    let instance = LXAssembly.LXFacade(isCHS: true)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    // Normal reading key should return nonKanji but NOT letterPunctuations.
    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(gramsContainValue(grams4A, "あ"))
    #expect(!gramsContainValue(grams4A, "，"))

    // Underscore key should return letterPunctuations.
    let grams4Punct = instance.unigramsFor(keyArray: ["_punctuation_comma"])
    #expect(gramsContainValue(grams4Punct, "，"))
  }

  @Test
  func testETenDOSUnigramsDoNotReorderFactoryCoreResults() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄗㄞˋ", [
        (value: "在", probability: -5.004, typeID: 6),
        (value: "再", probability: -5.007, typeID: 6),
      ]),
    ])

    let instance = LXAssembly.LXFacade(isCHS: false)
    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))

    // Case 1: alwaysSupplyETenDOSUnigrams = false
    instance.setOptions { config in
      config.alwaysSupplyETenDOSUnigrams = false
    }
    let gramsWithoutETen = instance.unigramsFor(keyArray: ["ㄗㄞˋ"])
    let valuesWithoutETen = gramsWithoutETen.map(\.current)
    #expect(valuesWithoutETen.firstIndex(of: "在")! < valuesWithoutETen.firstIndex(of: "再")!)

    // Case 2: alwaysSupplyETenDOSUnigrams = true
    instance.setOptions { config in
      config.alwaysSupplyETenDOSUnigrams = true
    }
    let gramsWithETen = instance.unigramsFor(keyArray: ["ㄗㄞˋ"])
    let valuesWithETen = gramsWithETen.map(\.current)
    #expect(valuesWithETen.firstIndex(of: "在")! < valuesWithETen.firstIndex(of: "再")!)

    // Case 3: supplementalValues must return ETenDOS order (在 before 再)
    let supplemental = instance.lxQuerier.supplementalValues(for: "ㄗㄞˋ", strategy: .exactMatch)
    #expect(supplemental.firstIndex(of: "在")! < supplemental.firstIndex(of: "再")!)
  }

  @Test
  func testCartesianProductBudgetGateSkipsExpansionBeyondBudget() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("ㄚㄚ-ㄅㄅ", [("factoryHit", -9.9, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    instance.setOptions { config in
      config.bypassUserPhrasesData = false
      config.isSymbolEnabled = false
      config.alwaysSupplyETenDOSUnigrams = false
      config.isCNSEnabled = false
      config.filterNonCNSReadings = false
      config.partialMatchEnabled = false
    }
    // 使用者片語鍵不可含半形英數（PinyinPhonaConverter 會將其轉成注音/聲調記號）。
    // 注意：lxUserPhrases 以 reverse:true 建構，檔案行格式為「詞語 讀音 分數」。
    instance.injectTestData(
      userPhrases: { $0.replaceData(textData: "使用者命中 ㄚㄚ-ㄅㄅ -8\n另一條 ㄚㄚ-ㄅㄒ -8\n") }
    )

    // 預算內（2 × 1 = 2）：逐組合展開照常進行，使用者片語與原廠路徑皆可命中。
    let small = instance.lxQuerier.grams(for: [
      .multipleKeys(["ㄚㄚ", "ㄒㄒ"]), .singleKey("ㄅㄅ"),
    ])
    #expect(gramsContainValue(small, "使用者命中"))
    #expect(gramsContainValue(small, "factoryHit"))

    // 超預算（100 × 101 = 10,100 > 625）：放棄逐組合展開，使用者片語不再被查詢；
    // 原廠 "&" 連讀查詢路徑（O(候選節點) 而非 O(乘積)）依然有效。
    let bigA = Array(repeating: "ㄚㄚ", count: 100)
    let bigB = Array(repeating: "ㄅㄅ", count: 101)
    let big = instance.lxQuerier.grams(for: [
      .multipleKeys(bigA), .multipleKeys(bigB),
    ])
    #expect(!gramsContainValue(big, "使用者命中"))
    #expect(!gramsContainValue(big, "另一條"))
    #expect(gramsContainValue(big, "factoryHit"))
  }

  @Test
  func testAbbreviatedWordCandidatesReachesWholeWord() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("ㄧㄝ-ㄕㄡ-ㄒㄧㄢ-ㄅㄟ", [("野獸先輩", -3.0, 5)]),
      ("ㄧㄠ-ㄕㄨ-ㄒㄧㄥ-ㄅㄢ", [("遙梳星班", -4.0, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    instance.setOptions { config in
      config.bypassUserPhrasesData = false
      config.isSymbolEnabled = false
      config.alwaysSupplyETenDOSUnigrams = false
      config.isCNSEnabled = false
      config.filterNonCNSReadings = false
      config.partialMatchEnabled = false // 整詞簡拼查詢恆為 partial 語義、與此偏好無關。
    }
    // 使用者造詞（reverse: true 格式「詞語 讀音 分數」）：位置 0 以「ㄩ」命中。
    instance.injectTestData(
      userPhrases: { $0.replaceData(textData: "遠收星冰 ㄩㄢ-ㄕㄡ-ㄒㄧㄥ-ㄅㄧㄥ -5\n") }
    )

    // 「ysxb」→ chop → deduct → initial 類 cells。
    let cells = ["ㄧ&ㄩ", "ㄕ&ㄙ", "ㄒ", "ㄅ"]
    let grams = instance.lxQuerier.abbreviatedWordCandidates(keysChopped: cells)
    let values = grams.map(\.current)

    // factory「&」逐位置前綴命中（含實際讀音 keyArray，供單鍵寫回）。
    #expect(values.contains("野獸先輩"))
    #expect(values.contains("遙梳星班"))
    #expect(grams.first(where: { $0.current == "野獸先輩" })?.keyArray == ["ㄧㄝ", "ㄕㄡ", "ㄒㄧㄢ", "ㄅㄟ"])
    // user-phrase 多前綴掃描命中。
    #expect(values.contains("遠收星冰"))
    // 分區順序：factory 命中在前（野獸先輩 -3 於遙梳星班 -4 之前）。
    let firstYeShou = try #require(values.firstIndex(of: "野獸先輩"))
    let firstYaoShu = try #require(values.firstIndex(of: "遙梳星班"))
    #expect(firstYeShou < firstYaoShu)
  }

  /// 整詞簡拼查詢之界線：**候選段數不得多於格數**（上界；每格對應詞內一個位置）。
  ///
  /// 原廠辭典側本即等段匹配（trie 之 `longerSegment: false`）；使用者片語側所走的多位置
  /// 前綴掃描則是通用前綴 API、刻意忽略多出的段 ⇒ 若不在查詢端收斂，兩格之查詢會撈回
  /// 三音節之使用者造詞（狂打 copilot 窗因而顯示／寫入使用者從未敲下之音節）。
  /// 本靶以同一組讀音同時釘住兩分區、逐格數驗上界（2 格／3 格）。
  /// 另釘「短於格數者亦不命中」——該側不是本查詢所收斂者，而是兩分區掃描自身之
  /// 「覆蓋全部格」要求；它為下游套用路徑之前提（候選之讀音須覆蓋使用者所敲之格）。
  @Test
  func testAbbreviatedWordCandidatesRespectCellCountUpperBound() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("ㄎㄜ-ㄐㄧˋ", [("科技", -3.0, 5)]),
      ("ㄎㄜ-ㄐㄧˋ-ㄐㄧㄤˇ", [("科技江", -3.5, 5)]),
      ("ㄎㄜ-ㄐㄧˋ-ㄐㄧㄤˇ-ㄈㄨˊ", [("科技江福", -3.8, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    instance.setOptions { config in
      config.bypassUserPhrasesData = false
      config.isSymbolEnabled = false
      config.alwaysSupplyETenDOSUnigrams = false
      config.isCNSEnabled = false
      config.filterNonCNSReadings = false
      config.partialMatchEnabled = false // 整詞簡拼查詢恆為 partial 語義、與此偏好無關。
    }
    // 使用者造詞（reverse: true 格式「詞語 讀音 分數」）：兩分區各取不同詞值，
    // 俾「誰命中、誰未命中」不被去重遮蔽。
    instance.injectTestData(
      userPhrases: { $0.replaceData(textData: "科技獎 ㄎㄜ-ㄐㄧˋ-ㄐㄧㄤˇ -6\n科記 ㄎㄜ-ㄐㄧˋ -6.5\n") }
    )

    // 兩格：兩音節者（原廠 ＋ 使用者片語）命中；三音節以上者（長於格數）皆不得命中。
    let twoCellValues = instance.lxQuerier
      .abbreviatedWordCandidates(keysChopped: ["ㄎ", "ㄐ"]).map(\.current)
    #expect(twoCellValues.contains("科技"), "實得：\(twoCellValues)")
    #expect(twoCellValues.contains("科記"), "實得：\(twoCellValues)")
    #expect(!twoCellValues.contains("科技獎"), "實得：\(twoCellValues)")
    #expect(!twoCellValues.contains("科技江"), "實得：\(twoCellValues)")
    #expect(!twoCellValues.contains("科技江福"), "實得：\(twoCellValues)")

    // 三格：三音節者命中（四音節者仍不得命中）；兩音節者（短於格數）亦不命中。
    let threeCellValues = instance.lxQuerier
      .abbreviatedWordCandidates(keysChopped: ["ㄎ", "ㄐ", "ㄐ"]).map(\.current)
    #expect(threeCellValues.contains("科技獎"), "實得：\(threeCellValues)")
    #expect(threeCellValues.contains("科技江"), "實得：\(threeCellValues)")
    #expect(!threeCellValues.contains("科技江福"), "實得：\(threeCellValues)")
    #expect(!threeCellValues.contains("科技"), "實得：\(threeCellValues)")
    #expect(!threeCellValues.contains("科記"), "實得：\(threeCellValues)")
  }

  /// 控頻：整詞簡拼查詢內**雷同之詞音配對**（同值同讀音）者，其權重以使用者辭典者為最優先。
  ///
  /// 通用查詢路徑以「使用者片語置前 ＋ `consolidate` 先插入者勝」實現此語義；本查詢之呈現
  /// 順序係分區制，故以使用者側之條目就地取代同配對之原廠條目。本靶驗三事：
  /// ① 原廠之權重遭使用者側覆寫（升頻）；② 覆寫亦可用於降頻（雙向）；③ 非雷同者
  /// （同值而異讀音）不在覆寫之列。
  @Test
  func testAbbreviatedWordCandidatesUserPhrasesControlFrequency() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("ㄎㄜ-ㄐㄧˋ", [("科技", -3.0, 5)]),
      ("ㄎㄜ-ㄐㄧˊ", [("科吉", -6.0, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    instance.setOptions { config in
      config.bypassUserPhrasesData = false
      config.isSymbolEnabled = false
      config.alwaysSupplyETenDOSUnigrams = false
      config.isCNSEnabled = false
      config.filterNonCNSReadings = false
      config.partialMatchEnabled = false // 整詞簡拼查詢恆為 partial 語義、與此偏好無關。
    }

    /// 以給定之使用者造詞重查，回傳「科技」之權重與整份清單之詞值序。
    func query(userPhrases: String) -> (weight: Double?, values: [String]) {
      instance.injectTestData(userPhrases: { $0.replaceData(textData: userPhrases) })
      let grams = instance.lxQuerier.abbreviatedWordCandidates(keysChopped: ["ㄎ", "ㄐ"])
      return (
        grams.first(where: { $0.current == "科技" })?.probability,
        grams.map(\.current)
      )
    }

    // ⓪ 基線：原廠之權重（-3.0）居首。
    let baseline = query(userPhrases: "")
    #expect(baseline.weight == -3.0, "實得：\(baseline.weight as Any)")
    #expect(baseline.values == ["科技", "科吉"], "實得：\(baseline.values)")

    // ① 升頻：雷同之詞音配對（同值同讀音）⇒ 權重取使用者側（-0.5）。
    let boosted = query(userPhrases: "科技 ㄎㄜ-ㄐㄧˋ -0.5\n")
    #expect(boosted.weight == -0.5, "實得：\(boosted.weight as Any)")
    #expect(boosted.values == ["科技", "科吉"], "實得：\(boosted.values)")

    // ② 降頻：同一配對之使用者權重低於其他原廠命中 ⇒ 沉於其後（覆寫為雙向）。
    let demoted = query(userPhrases: "科技 ㄎㄜ-ㄐㄧˋ -9.0\n")
    #expect(demoted.weight == -9.0, "實得：\(demoted.weight as Any)")
    #expect(demoted.values == ["科吉", "科技"], "實得：\(demoted.values)")

    // ③ 界線：同值而異讀音（ㄎㄜ-ㄐㄧˊ）者非「雷同之詞音配對」⇒ 不覆寫；
    //    該使用者條目另因依詞值去重而讓位於原廠條目。
    let mismatched = query(userPhrases: "科技 ㄎㄜ-ㄐㄧˊ -0.5\n")
    #expect(mismatched.weight == -3.0, "實得：\(mismatched.weight as Any)")
    #expect(mismatched.values == ["科技", "科吉"], "實得：\(mismatched.values)")
  }

  /// 整詞簡拼查詢之回傳序即**分數序**（跨原廠與使用者片語兩來源合併排序）。
  ///
  /// 事主 2026-09-28 之裁定：「被降頻之原廠詞也不該壓過分數更高的使用者片語」——故本查詢
  /// **不得**再現「原廠區塊先、其後使用者片語區塊」之分區陳列；去重仍以原廠側之讀音優先
  /// （同值者），惟排序一律按（覆寫後之）分數。本靶以兩來源交錯之分數為測資。
  @Test
  func testAbbreviatedWordCandidatesOrderByScoreAcrossSources() throws {
    defer {
      LXAssembly.LXFacade.disconnectFactoryDictionary()
    }

    let instance = LXAssembly.LXFacade(isCHS: true)
    let textMap = makeTextMap([
      ("ㄎㄜ-ㄐㄧˋ", [("科技", -3.0, 5)]),
      ("ㄎㄜ-ㄐㄧˊ", [("科吉", -6.0, 5)]),
    ])

    #expect(LXAssembly.LXFacade.connectToTestFactoryDictionary(textMapData: textMap))
    instance.setOptions { config in
      config.bypassUserPhrasesData = false
      config.isSymbolEnabled = false
      config.alwaysSupplyETenDOSUnigrams = false
      config.isCNSEnabled = false
      config.filterNonCNSReadings = false
      config.partialMatchEnabled = false
    }
    // 使用者側：一筆專有詞（科記 −4.0，分數居中）＋ 一筆對原廠「科技」之降頻（−9.0）。
    instance.injectTestData(
      userPhrases: { $0.replaceData(textData: "科記 ㄎㄜ-ㄐㄧˋ -4.0\n科技 ㄎㄜ-ㄐㄧˋ -9.0\n") }
    )

    let grams = instance.lxQuerier.abbreviatedWordCandidates(keysChopped: ["ㄎ", "ㄐ"])
    #expect(grams.map(\.current) == ["科記", "科吉", "科技"], "實得：\(grams.map(\.current))")
    #expect(grams.map(\.probability) == [-4.0, -6.0, -9.0], "實得：\(grams.map(\.probability))")
    // 去重仍生效：同值者僅一筆，且其權重為使用者側之降頻值。
    #expect(grams.filter { $0.current == "科技" }.count == 1, "實得：\(grams.map(\.current))")
  }

  // MARK: Private

  private struct GramSnapshot: Equatable, Hashable {
    // MARK: Lifecycle

    init(_ gram: Homa.Gram) {
      self.keyArray = gram.keyArray
      self.value = gram.current
      self.probability = gram.probability
    }

    init(keyArray: [String], value: String, probability: Double) {
      self.keyArray = keyArray
      self.value = value
      self.probability = probability
    }

    // MARK: Internal

    let keyArray: [String]
    let value: String
    let probability: Double
  }

  private func gramsContainValue(_ grams: [Homa.Gram], _ value: String) -> Bool {
    grams.contains(where: { $0.current == value })
  }

  private func gramTriple(of gram: Homa.Gram?) -> GramSnapshot? {
    gram.map(GramSnapshot.init)
  }

  private func gramTriples(of grams: [Homa.Gram]) -> [GramSnapshot] {
    grams.map(GramSnapshot.init)
  }

  private func makeTextMap(_ entriesByKey: [(String, [(value: String, probability: Double, typeID: Int32)])])
    -> String {
    var valueLines: [String] = []
    var keyLines: [String] = []

    for (key, entries) in entriesByKey {
      let startLine = valueLines.count
      entries.forEach { entry in
        let probabilityText = entry.probability.description.hasSuffix(".0")
          ? String(entry.probability.description.dropLast(2))
          : entry.probability.description
        valueLines.append("\(entry.value)\t\(probabilityText)\t\(entry.typeID)")
      }
      keyLines.append("\(key)\t\(startLine)\t\(entries.count)")
    }

    var result = ""
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\n"
    result += "VERSION\t1.1\n"
    result += "TYPE\tTYPING\n"
    result += "READING_SEPARATOR\t-\n"
    result += "ENTRY_COUNT\t\(valueLines.count)\n"
    result += "KEY_COUNT\t\(keyLines.count)\n"
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\n"
    valueLines.forEach { result += $0 + "\n" }
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\n"
    keyLines.forEach { result += $0 + "\n" }
    return result
  }
}
