// (c) 2021 and onwards The vChewing Project (MIT-NTL License).
// ====================
// This code is released under the MIT license (SPDX-License-Identifier: MIT)
// ... with NTL restriction stating that:
// No trademark license is granted to use the trade names, trademarks, service
// marks, or product names of Contributor, except as required to fulfill notice
// requirements defined in MIT License.

import Foundation
import LMAssemblyMaterials4Tests
import Megrez
import Testing

@testable import LangModelAssembly

private let strCakeKey: [String] = ["ㄉㄢˋ", "ㄍㄠ"]
private let strZhongKey: [String] = ["ㄓㄨㄥ"]
private let strBoobsKey: [String] = ["ㄋㄟ", "ㄋㄟ"]
private let expectedReverseLookupResults: [String] = [
  "ㄉㄨㄥ", "ㄏㄢˋ", "ㄏㄜˊ", "ㄏㄜˋ", "ㄏㄨˊ", "ㄏㄨㄛˋ", "ㄏㄨㄛ˙",
]

// MARK: - LMInstantiatorTextMapTests

@Suite(.serialized)
struct LMInstantiatorTextMapTests {
  // MARK: Internal

  @Test
  func testTextMapFixtureLoading() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(!LMATestsData.textMapTestCoreLMData.isEmpty)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
    }
    #expect(instance.unigramsFor(keyArray: strCakeKey).description == "[(ㄉㄢˋ-ㄍㄠ,蛋糕,-4.073)]")
    #expect(instance.getHaninSymbolMenuUnigrams()[1].description == "(_punctuation_list,，,-9.9)")
    #expect(instance.unigramsFor(keyArray: strBoobsKey).description == "[(ㄋㄟ-ㄋㄟ,ㄋㄟㄋㄟ,-1.0)]")

    instance.setOptions { config in
      config.isCNSEnabled = true
      config.isSymbolEnabled = true
    }
    #expect(instance.unigramsFor(keyArray: strCakeKey).last?.description == "(ㄉㄢˋ-ㄍㄠ,🧁,-13.000001)")
    #expect(instance.unigramsFor(keyArray: strZhongKey).count == 21)
    #expect(instance.unigramsFor(keyArray: strBoobsKey).last?.description == "(ㄋㄟ-ㄋㄟ,☉☉,-13.0)")
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testLegacyTestLoaderCompatibility() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    #expect(!LMATestsData.sqlTestCoreLMData.isEmpty)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.sqlTestCoreLMData))
    #expect(instance.unigramsFor(keyArray: strCakeKey).first?.value == "蛋糕")
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testCNSMask() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
      config.filterNonCNSReadings = false
      config.alwaysSupplyETenDOSUnigrams = false
    }
    #expect(instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.value == "危" })?.description == "(ㄨㄟ,危,-5.287)")
    #expect(instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.value == "危" })?.description == "(ㄨㄟˊ,危,-5.287)")

    instance.setOptions { config in
      config.filterNonCNSReadings = true
    }
    // 單一讀音的單漢字不再被濾除，而是 demote score 至 -9.5。
    #expect(instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.value == "危" })?.description == "(ㄨㄟ,危,-9.5)")
    #expect(instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.value == "危" })?.description == "(ㄨㄟˊ,危,-5.287)")
  }

  @Test
  func testFactoryKeyWithApostropheIsFound() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("k'", [("1 value", -9.9, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["k'"]), "1 value"))
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedOrderIsStable() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t2
    KEY_COUNT\t2
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t和\t和
    @-9.9\t和\t和
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    he4\t0\t1
    huo4\t1\t1
    """

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ", "ㄏㄨㄛˋ"])
  }

  @Test
  func testFactoryTextMapLoadsWithCRLFLineEndings() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap =
      "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\r\nVERSION\t1\r\nTYPE\tTYPING\r\nREADING_SEPARATOR\t-\r\nENTRY_COUNT\t1\r\nKEY_COUNT\t1\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\r\n@-9.9\t和\t和\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\r\nhe4\t0\t1\r\n"

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ"])
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedUsesSingleSegmentGroupedLinesAndCNSEntries() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t3
    KEY_COUNT\t3
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t宜\t宜
    @-8.8\t便宜\t便宜
    𡜅	-11	7
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    i2\t0\t1
    bi4-i2\t1\t1
    lv3\t2\t1
    """

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "宜") == ["ㄧˊ"])
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "𡜅") == ["ㄌㄩˇ"])
  }

  @Test
  func testFactoryDictionaryDoesNotAutoLoadRevLookupFile() throws {
    let tempDir = FileManager.default.temporaryDirectory
      .appendingPathComponent(UUID().uuidString)
    try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    defer {
      try? FileManager.default.removeItem(at: tempDir)
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMapPath = tempDir.appendingPathComponent("VanguardFactoryDict4Typing.txtMap")
    let revLookupPath = tempDir.appendingPathComponent("VanguardFactoryDict4RevLookup.revlookup")
    let textMap = makeTextMap([
      ("A", [("和", -9.9, 5)]),
    ])
    let revLookup = "#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\tB\n"

    try textMap.write(to: textMapPath, atomically: true, encoding: .utf8)
    try revLookup.write(to: revLookupPath, atomically: true, encoding: .utf8)

    #expect(LMAssembly.LMInstantiator.connectFactoryDictionary(textMapPath: textMapPath.path))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "B") == nil)
  }

  @Test
  func testFactoryDictionaryRejectsBundledExternalRevLookupFixture() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let bundledFixture = LMATestsData.textMapTestCoreLMData
      + "\n#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\the4\n"

    #expect(!LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: bundledFixture))
    #expect(!LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: bundledFixture))
  }

  @Test
  func testFactoryCNSAndExistenceWithApostropheKey() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("k'", [("chtval", -9.9, 6), ("cnsval", -11, 7)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(instance.factoryCNSFilterThreadFor(key: "k'") == "cnsval")
    #expect(instance.hasFactoryCoreUnigramsFor(keyArray: ["k'"]))
  }

  @Test
  func testUnderscoreSpecialKeysUseMiscColumn() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("_alt_punctuation_,", [("，", -9.9, 4)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["_alt_punctuation_,"]), "，"))
    #expect(instance.hasUnigramsFor(keyArray: ["_alt_punctuation_,"]))
  }

  @Test
  func testFactorySupersetUnigramsFor() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("A-B-C", [("base", -9, 5)]),
      ("Z-A-B-C", [("zval", -1, 5)]),
      ("A-B-C-F", [("fval", -2, 5)]),
      ("M-A-B-C-Q", [("mval", -3, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    let grams = instance.factorySupersetUnigramsFor(
      subsetKey: "A-B-C",
      subsetKeyArray: ["A", "B", "C"],
      column: .theDataCHS
    )

    #expect(gramsContainValue(grams, "zval"))
    #expect(gramsContainValue(grams, "fval"))
    #expect(gramsContainValue(grams, "mval"))
    #expect(!gramsContainValue(grams, "base"))
    #expect(grams.first(where: { $0.value == "zval" })?.keyArray.count == 4)
  }

  @Test
  func testSQLiteDependencyRemoved() throws {
    let packageRoot = URL(fileURLWithPath: #filePath)
      .deletingLastPathComponent()
      .deletingLastPathComponent()
      .deletingLastPathComponent()
    let packageManifest = packageRoot.appendingPathComponent("Package.swift")
    let legacyExtension = packageRoot
      .appendingPathComponent("Sources")
      .appendingPathComponent("LangModelAssembly")
      .appendingPathComponent("LMInstantiator_SQLExtension.swift")

    let manifestContents = try String(contentsOf: packageManifest, encoding: .utf8)
    #expect(!manifestContents.contains("CSQLite3Lib"))
    #expect(!FileManager.default.fileExists(atPath: legacyExtension.path))
  }

  // MARK: Private

  private func gramsContainValue(_ grams: [Megrez.Unigram], _ value: String) -> Bool {
    grams.contains(where: { $0.value == value })
  }

  private func makeTextMap(_ entriesByKey: [(String, [(value: String, probability: Double, typeID: Int32)])])
    -> String {
    var valueLines: [String] = []
    var keyLines: [String] = []

    for (key, entries) in entriesByKey {
      let startLine = valueLines.count
      entries.forEach { entry in
        let probabilityText = entry.probability.description.hasSuffix(".0")
          ? String(entry.probability.description.dropLast(2))
          : entry.probability.description
        valueLines.append("\(entry.value)\t\(probabilityText)\t\(entry.typeID)")
      }
      keyLines.append("\(key)\t\(startLine)\t\(entries.count)")
    }

    var result = ""
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\n"
    result += "VERSION\t1\n"
    result += "TYPE\tTYPING\n"
    result += "READING_SEPARATOR\t-\n"
    result += "ENTRY_COUNT\t\(valueLines.count)\n"
    result += "KEY_COUNT\t\(keyLines.count)\n"
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\n"
    valueLines.forEach { result += $0 + "\n" }
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\n"
    keyLines.forEach { result += $0 + "\n" }
    return result
  }
}
