// (c) 2021 and onwards The vChewing Project (MIT-NTL License).
// ====================
// This code is released under the MIT license (SPDX-License-Identifier: MIT)
// ... with NTL restriction stating that:
// No trademark license is granted to use the trade names, trademarks, service
// marks, or product names of Contributor, except as required to fulfill notice
// requirements defined in MIT License.

import Foundation
import Homa
import LMAssemblyMaterials4Tests
import Testing

@testable import LangModelAssembly

private let strCakeKey: [String] = ["ㄉㄢˋ", "ㄍㄠ"]
private let strZhongKey: [String] = ["ㄓㄨㄥ"]
private let strBoobsKey: [String] = ["ㄋㄟ", "ㄋㄟ"]
private let expectedReverseLookupResults: [String] = [
  "ㄉㄨㄥ", "ㄏㄢˋ", "ㄏㄜˊ", "ㄏㄜˋ", "ㄏㄜ˙", "ㄏㄨˊ", "ㄏㄨㄛ", "ㄏㄨㄛˊ", "ㄏㄨㄛˋ", "ㄏㄨㄛ˙",
]

// MARK: - LMInstantiatorTextMapTests

@Suite(.serialized)
struct LMInstantiatorTextMapTests {
  // MARK: Internal

  @Test
  func testTextMapFixtureLoading() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(!LMATestsData.textMapTestCoreLMData.isEmpty)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
    }
    #expect(gramTriples(of: instance.unigramsFor(keyArray: strCakeKey)) == [
      .init(keyArray: strCakeKey, value: "蛋糕", probability: -4.072),
    ])
    #expect(gramTriple(of: instance.getHaninSymbolMenuUnigrams()[1]) == .init(
      keyArray: ["_punctuation_list"],
      value: "，",
      probability: 0.0
    ))
    #expect(gramTriples(of: instance.unigramsFor(keyArray: strBoobsKey)) == [
      .init(keyArray: strBoobsKey, value: "ㄋㄟㄋㄟ", probability: -1.0),
    ])

    instance.setOptions { config in
      config.isCNSEnabled = true
      config.isSymbolEnabled = true
    }
    #expect(gramTriple(of: instance.unigramsFor(keyArray: strCakeKey).last) == .init(
      keyArray: strCakeKey,
      value: "🧁",
      probability: -13.0
    ))
    #expect(instance.unigramsFor(keyArray: strZhongKey).count == 184)
    #expect(gramTriple(of: instance.unigramsFor(keyArray: strBoobsKey).last) == .init(
      keyArray: strBoobsKey,
      value: "☉☉",
      probability: -13.0
    ))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testLegacyTestLoaderCompatibility() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    #expect(!LMATestsData.textMapTestCoreLMData.isEmpty)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))
    #expect(instance.unigramsFor(keyArray: strCakeKey).first?.current == "蛋糕")
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == expectedReverseLookupResults)
  }

  @Test
  func testCNSMask() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))

    instance.setOptions { config in
      config.isCNSEnabled = false
      config.isSymbolEnabled = false
      config.filterNonCNSReadings = false
      config.alwaysSupplyETenDOSUnigrams = false
    }
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟ"], value: "危", probability: -5.287)
    )
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟˊ"], value: "危", probability: -5.287)
    )

    instance.setOptions { config in
      config.filterNonCNSReadings = true
    }
    // 單一讀音的單漢字不再被濾除，而是 demote score 至 -9.5。
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟ"], value: "危", probability: -9.5)
    )
    #expect(
      gramTriple(of: instance.unigramsFor(keyArray: ["ㄨㄟˊ"]).first(where: { $0.current == "危" })) ==
        .init(keyArray: ["ㄨㄟˊ"], value: "危", probability: -5.287)
    )
  }

  @Test
  func testFactoryKeyWithApostropheIsFound() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("k'", [("1 value", -9.9, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["k'"]), "1 value"))
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedOrderIsStable() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1.1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t2
    KEY_COUNT\t2
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t和\t和
    @-9.9\t和\t和
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    ㄏㄜˋ\t0\t1
    ㄏㄨㄛˋ\t1\t1
    """

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ", "ㄏㄨㄛˋ"])
  }

  @Test
  func testFactoryTextMapLoadsWithCRLFLineEndings() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap =
      "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\r\nVERSION\t1.1\r\nTYPE\tTYPING\r\nREADING_SEPARATOR\t-\r\nENTRY_COUNT\t1\r\nKEY_COUNT\t1\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\r\n@-9.9\t和\t和\r\n#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\r\nㄏㄜˋ\t0\t1\r\n"

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "和") == ["ㄏㄜˋ"])
  }

  @Test
  func testFactoryReverseLookupAutoGeneratedUsesSingleSegmentGroupedLinesAndCNSEntries() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = """
    #PRAGMA:VANGUARD_HOMA_LEXICON_HEADER
    VERSION\t1.1
    TYPE\tTYPING
    READING_SEPARATOR\t-
    ENTRY_COUNT\t3
    KEY_COUNT\t3
    #PRAGMA:VANGUARD_HOMA_LEXICON_VALUES
    @-9.9\t宜\t宜
    @-8.8\t便宜\t便宜
    𡜅	-11	7
    #PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP
    ㄧˊ\t0\t1
    ㄅㄧˋ-ㄧˊ\t1\t1
    ㄌㄩˇ\t2\t1
    """

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "宜") == ["ㄧˊ"])
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "𡜅") == ["ㄌㄩˇ"])
  }

  @Test
  func testFactoryDictionaryDoesNotAutoLoadRevLookupFile() async throws {
    let tempDir = FileManager.default.temporaryDirectory
      .appendingPathComponent(UUID().uuidString)
    try FileManager.default.createDirectory(at: tempDir, withIntermediateDirectories: true)
    defer {
      try? FileManager.default.removeItem(at: tempDir)
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMapPath = tempDir.appendingPathComponent("VanguardFactoryDict4Typing.txtMap")
    let revLookupPath = tempDir.appendingPathComponent("VanguardFactoryDict4RevLookup.revlookup")
    let textMap = makeTextMap([
      ("A", [("和", -9.9, 5)]),
    ])
    let revLookup = "#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\tB\n"

    try textMap.write(to: textMapPath, atomically: true, encoding: .utf8)
    try revLookup.write(to: revLookupPath, atomically: true, encoding: .utf8)

    let originalAsyncLoading = LMAssembly.LMInstantiator.asyncLoadingUserData
    LMAssembly.LMInstantiator.asyncLoadingUserData = false
    defer {
      LMAssembly.LMInstantiator.asyncLoadingUserData = originalAsyncLoading
    }

    let callbackResult: Bool? = await withCheckedContinuation { continuation in
      LMAssembly.LMInstantiator.connectFactoryDictionary(textMapPath: textMapPath.path) {
        continuation.resume(returning: $0)
      }
    }

    #expect(callbackResult == true)
    #expect(LMAssembly.LMInstantiator.getFactoryReverseLookupData(with: "B") == nil)
  }

  @Test
  func testFactoryDictionaryRejectsBundledExternalRevLookupFixture() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let bundledFixture = LMATestsData.textMapTestCoreLMData
      + "\n#PRAGMA:VANGUARD_REVLOOKUP_TSV\nVERSION\t1\n和\the4\n"

    #expect(!LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: bundledFixture))
    #expect(!LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: bundledFixture))
  }

  @Test
  func testFactoryCNSAndExistenceWithApostropheKey() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("k'", [("chtval", -9.9, 6), ("cnsval", -11, 7)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(instance.factoryCNSFilterThreadFor(key: "k'") == "cnsval")
    #expect(instance.hasFactoryCoreUnigramsFor(keyArray: ["k'"]))
  }

  @Test
  func testUnderscoreSpecialKeysUseMiscColumn() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("_alt_punctuation_,", [("，", -9.9, 4)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["_alt_punctuation_,"]), "，"))
    #expect(instance.hasUnigramsFor(keyArray: ["_alt_punctuation_,"]))
  }

  @Test
  func testGeneratedHalfWidthPunctuationRanksBehindCanonicalFullWidth() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("_punctuation_,", [("，", -9.9, 4)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    let grams = instance.unigramsFor(keyArray: ["_punctuation_,"])
    let fullWidth = grams.first(where: { $0.current == "，" })
    let halfWidth = grams.first(where: { $0.current == "," })

    #expect(gramTriple(of: fullWidth) == .init(keyArray: ["_punctuation_,"], value: "，", probability: -9.9))
    #expect(gramTriple(of: halfWidth) == .init(keyArray: ["_punctuation_,"], value: ",", probability: -9.9001))
  }

  @Test
  func testEqualScoreStandardPunctuationPreservesLexiconOrder() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: false)
    let textMap = makeTextMap([
      ("_punctuation_Standard_<", [("，", -9.9, 4), ("〈", -9.9, 4), ("《", -9.9, 4)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    let grams = instance.unigramsFor(keyArray: ["_punctuation_Standard_<"])
    #expect(grams.map(\.current).prefix(3).elementsEqual(["，", "〈", "《"]))
    #expect(grams.prefix(3).allSatisfy { $0.probability == -9.9 })
  }

  @Test
  func testFactoryStrictSupersetUnigramsFor() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("A-B-C", [("base", -9, 5)]),
      ("A-B-C-Z", [("zval", -1, 5)]),
      ("A-B-C-F", [("fval", -2, 5)]),
      ("A-B-C-M-Q", [("mval", -3, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))
    let grams = instance.factoryStrictSupersetUnigramsFor(
      subsetKey: "A-B-C",
      subsetKeyArray: ["A", "B", "C"],
      column: .theDataCHS
    )

    #expect(gramsContainValue(grams, "zval"))
    #expect(gramsContainValue(grams, "fval"))
    #expect(gramsContainValue(grams, "mval"))
    #expect(!gramsContainValue(grams, "base"))
    #expect(grams.first(where: { $0.current == "zval" })?.keyArray.count == 4)
  }

  @Test
  func testFactoryPartialMatchIsControlledByConfigFlag() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("A1-B2", [("partial", -9.9, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.alwaysSupplyETenDOSUnigrams = false
      config.partialMatchEnabled = false
    }
    #expect(instance.unigramsFor(keyArray: ["A&X", "B"]).isEmpty)
    #expect(!instance.hasFactoryCoreUnigramsFor(keyArray: ["A&X", "B"]))

    instance.setOptions { config in
      config.partialMatchEnabled = true
    }
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["A&X", "B"]), "partial"))
    #expect(instance.hasFactoryCoreUnigramsFor(keyArray: ["A&X", "B"]))
  }

  @Test
  func testStrictSupersetStrategyRemainsDistinctFromConfiguredPartialLookup() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    let textMap = makeTextMap([
      ("A1-B2", [("exact", -9.9, 5)]),
      ("A1-B2-C3", [("superset", -8.8, 5)]),
    ])

    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.partialMatchEnabled = true
    }

    let configuredLookup = instance.factoryCoreUnigramsFor(
      key: "A1-B2",
      keyArray: ["A1", "B2"],
      strategy: .configuredLookup
    )
    let strictSupersets = instance.factoryCoreUnigramsFor(
      key: "A1-B2",
      keyArray: ["A1", "B2"],
      strategy: .strictSuperset
    )

    #expect(gramsContainValue(configuredLookup, "exact"))
    #expect(!gramsContainValue(configuredLookup, "superset"))
    #expect(gramsContainValue(strictSupersets, "superset"))
    #expect(!gramsContainValue(strictSupersets, "exact"))
  }

  @Test
  func testAssemblerFacadeMatchesLegacyUnigramSurface() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: LMATestsData.textMapTestCoreLMData))

    instance.setOptions { config in
      config.isCNSEnabled = true
      config.isSymbolEnabled = true
    }

    let legacySurface = gramTriples(of: instance.unigramsFor(keyArray: strCakeKey))
    let assemblerSurface = instance.lookupHub.grams(for: strCakeKey).map {
      GramSnapshot(keyArray: $0.keyArray, value: $0.value, probability: $0.probability)
    }

    #expect(assemblerSurface == legacySurface)
    #expect(instance.lookupHub.grams(for: strCakeKey).allSatisfy { $0.previous == nil })
    #expect(instance.lookupHub.hasGrams(for: strCakeKey) == instance.hasUnigramsFor(keyArray: strCakeKey))
  }

  @Test
  func testNonKanjiHiraganaAndFWZeroAreQueryableViaNormalReading() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -13.0, typeID: 8),
        (value: "ぁ", probability: -13.0, typeID: 8),
      ]),
      ("ㄌㄧㄥˊ", [
        (value: "零", probability: -5.0, typeID: 5),
        (value: "〇", probability: -5.261, typeID: 8),
      ]),
    ])

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(gramsContainValue(grams4A, "あ"))
    #expect(gramsContainValue(grams4A, "ぁ"))

    let grams4Ling = instance.unigramsFor(keyArray: ["ㄌㄧㄥˊ"])
    #expect(gramsContainValue(grams4Ling, "零"))
    #expect(gramsContainValue(grams4Ling, "〇"))

    #expect(instance.hasUnigramsForFast(keyArray: ["ㄚ"]))
    #expect(instance.hasUnigramsForFast(keyArray: ["ㄌㄧㄥˊ"]))
  }

  @Test
  func testSuppressFactoryKanaSyllablesCanBeToggled() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -1.0, typeID: 8),
      ]),
      ("kana_only_i", [
        (value: "い", probability: -1.0, typeID: 8),
      ]),
      ("ㄎㄧㄚ", [
        (value: "家", probability: -5.0, typeID: 5),
        (value: "きゃ", probability: -2.0, typeID: 8),
      ]),
      ("ㄌㄧㄥˊ", [
        (value: "零", probability: -5.0, typeID: 5),
        (value: "〇", probability: -5.261, typeID: 8),
      ]),
    ])

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    instance.setOptions { config in
      config.suppressFactoryUnigramsOfKanaSyllables = false
    }
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["ㄚ"]), "あ"))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["kana_only_i"]), "い"))
    #expect(gramsContainValue(instance.unigramsFor(keyArray: ["ㄎㄧㄚ"]), "きゃ"))
    #expect(instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))

    instance.setOptions { config in
      config.suppressFactoryUnigramsOfKanaSyllables = true
    }

    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(!gramsContainValue(grams4A, "あ"))

    let grams4I = instance.unigramsFor(keyArray: ["kana_only_i"])
    #expect(grams4I.isEmpty)

    let grams4Kia = instance.unigramsFor(keyArray: ["ㄎㄧㄚ"])
    #expect(gramsContainValue(grams4Kia, "家"))
    #expect(!gramsContainValue(grams4Kia, "きゃ"))

    let grams4Ling = instance.unigramsFor(keyArray: ["ㄌㄧㄥˊ"])
    #expect(gramsContainValue(grams4Ling, "零"))
    #expect(gramsContainValue(grams4Ling, "〇"))

    #expect(!instance.hasUnigramsForFast(keyArray: ["kana_only_i"]))
  }

  @Test
  func testLetterPunctuationRemainsUnderscoreKeyed() throws {
    defer {
      LMAssembly.LMInstantiator.disconnectFactoryDictionary()
    }

    let textMap = makeTextMap([
      ("ㄚ", [
        (value: "阿", probability: -5.0, typeID: 5),
        (value: "あ", probability: -13.0, typeID: 8),
      ]),
      ("_punctuation_comma", [
        (value: "，", probability: 0.0, typeID: 4),
      ]),
    ])

    let instance = LMAssembly.LMInstantiator(isCHS: true)
    #expect(LMAssembly.LMInstantiator.connectToTestFactoryDictionary(textMapData: textMap))

    // Normal reading key should return nonKanji but NOT letterPunctuations.
    let grams4A = instance.unigramsFor(keyArray: ["ㄚ"])
    #expect(gramsContainValue(grams4A, "阿"))
    #expect(gramsContainValue(grams4A, "あ"))
    #expect(!gramsContainValue(grams4A, "，"))

    // Underscore key should return letterPunctuations.
    let grams4Punct = instance.unigramsFor(keyArray: ["_punctuation_comma"])
    #expect(gramsContainValue(grams4Punct, "，"))
  }

  // MARK: Private

  private struct GramSnapshot: Equatable, Hashable {
    // MARK: Lifecycle

    init(_ gram: Homa.Gram) {
      self.keyArray = gram.keyArray
      self.value = gram.current
      self.probability = gram.probability
    }

    init(keyArray: [String], value: String, probability: Double) {
      self.keyArray = keyArray
      self.value = value
      self.probability = probability
    }

    // MARK: Internal

    let keyArray: [String]
    let value: String
    let probability: Double
  }

  private func gramsContainValue(_ grams: [Homa.Gram], _ value: String) -> Bool {
    grams.contains(where: { $0.current == value })
  }

  private func gramTriple(of gram: Homa.Gram?) -> GramSnapshot? {
    gram.map(GramSnapshot.init)
  }

  private func gramTriples(of grams: [Homa.Gram]) -> [GramSnapshot] {
    grams.map(GramSnapshot.init)
  }

  private func makeTextMap(_ entriesByKey: [(String, [(value: String, probability: Double, typeID: Int32)])])
    -> String {
    var valueLines: [String] = []
    var keyLines: [String] = []

    for (key, entries) in entriesByKey {
      let startLine = valueLines.count
      entries.forEach { entry in
        let probabilityText = entry.probability.description.hasSuffix(".0")
          ? String(entry.probability.description.dropLast(2))
          : entry.probability.description
        valueLines.append("\(entry.value)\t\(probabilityText)\t\(entry.typeID)")
      }
      keyLines.append("\(key)\t\(startLine)\t\(entries.count)")
    }

    var result = ""
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_HEADER\n"
    result += "VERSION\t1.1\n"
    result += "TYPE\tTYPING\n"
    result += "READING_SEPARATOR\t-\n"
    result += "ENTRY_COUNT\t\(valueLines.count)\n"
    result += "KEY_COUNT\t\(keyLines.count)\n"
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_VALUES\n"
    valueLines.forEach { result += $0 + "\n" }
    result += "#PRAGMA:VANGUARD_HOMA_LEXICON_KEY_LINE_MAP\n"
    keyLines.forEach { result += $0 + "\n" }
    return result
  }
}
